releng/org.eclipse.xtext.contributor/Xtext.setup

With the new setup it is possible to select only a subset of the
projects. Each repository is a subproject. It is also possible to select
one project first and install the dev env, and later execute Oomph and
install another. Therefore select the "Overwrite" flag on the final
wizard page.
Buildship 2.0 is added to the installed tools and replaces STS Gradle
feature. Gradle metadata needs to be checked in for the Project Import
action. Otherwise import fails with exception and the setup process
stops.
A Working Set is defined per repository, except for Eclipse. Since the
xtext-eclipse project has quite many projects, I devided them into
"Eclipse", "Eclipse Features" and "Eclipse Examples". A Working Set
"Root Projects" collects the Build root projects of all repositories.
Java version is …

[issue#4] Fix Oomph Setup for new repository structure

---

org.eclipse.xtext.common.types.eclipse.tests/xtext.common.types.eclipse.tests.launch

It was still referring to common.types.tests

updated launch configuration for common.types.eclipse.tests

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/label/DefaultEObjectLabelProviderTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/label/AbstractLabelProvider.java

Closes #23 
Task-Url: https://github.com/eclipse/xtext-eclipse/issues/23

23: AbstractLabelProvider.convertToString(Object) handles CharSequence

---

org.eclipse.xtext.doc/contents/202_scripting.html

fixed outdated documentation in scripting language 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=444264

fixed outdated documentation in scripting language 

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting/PreferenceStoreWhitespaceInformationProvider.java

Calling file.exists() does not guarantee that when calling
file.getContents() the file still exists

[473887] Handle IResourceStatus.RESOURCE_NOT_FOUND exception

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

[464029] Fixed broken Xtext Grammar Quickfix regearding metamodelname

[464029] Fixed broken Xtext Grammar Quickfix regearding metamodelname

---

org.eclipse.xtext.doc/contents/301_grammarlanguage.html

[479915] Wrong documentation of refactoring for LL(*) grammar

[479915] Wrong documentation of refactoring for LL(*) grammar

---

org.eclipse.xtext.xtext.ui/plugin.xml

[499994] Moved Call Hierarchy View to Xtext Category

[499994] Moved Call Hierarchy View to Xtext Category

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/XbaseQuickfixProvider.java

[403018] Quickfix use === instead of == with null as argument

[403018] Quickfix use === instead of == with null as argument

---

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/refactoring/JdtRenameRefactoringProcessorFactory.java

Fixed issue with renaming private inferred methods and enum literals #76

Fixed issue with renaming private inferred methods and enum literals #76

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java

length can be <0 when the selection is TextSelection#NULL.

[461630] Add guard condition

---

org.eclipse.xtext.doc/contents/304_ide_concepts.html

[486001] Converted Proposal Provider Example Code in Docs to Xtend

[486001] Converted Proposal Provider Example Code in Docs to Xtend

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorActions.java

[392643] Enable  Select all in EmbeddedEditorActions wqfor embedded read-only editors

[392643] Enable  Select all in EmbeddedEditorActions for embedded read-only editors

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Xtext and Xtend must be both updated from the latest CI build. Since the
Xtend p2 repository was missing, Xtext could also not be updated.

[#83] Add CI p2 repository for Xtend

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/templates/XbaseTemplateContext.java

[462915] NPE when using 'Import' template variable extension and type is not on classpath
do state cleaning in evaluateForDisplay as well
Signed-off-by: Christian Dietrich christian.dietrich@itemis.de

[462915] NPE when using 'Import' template variable extension and typeis not on classpath

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Changed reference project, old reference project org.eclipse.xtext.sdk.feature was moved to other repo
Removed obsolete OrPredicate for natures

Fixed working sets for projects from xtext-eclipse

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Most projects have explicit encodings set, but we have to make sure that the encoding defaults to UTF-8.

Set workspace encoding to UTF-8

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Xtext repository moved from eclipse/xtext-eclipse to eclipse/xtext
Use last stable instead of last successful build

[#83] Repository location for Xtext & Xtend SDK changed

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Import projects and add them to working set "Releng"

Clone Xtext umbrella repository

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/actions/SortOutlineContribution.java

When changing the sorting, the complete tree needs to be refreshed.
Especially for big trees disabling all repainting during the update can
cut down the refresh time to half of before.
Signed-off-by: Michael Keppler <michael.keppler@gmx.de>

improve outline refresh performance

---

org.eclipse.xtext.xtext.ui.examples/projects/xbase.tutorial/src-gen/Xbase10_Switch.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=501975
Switch statements are guarded now

[501975] Generated Xtend code

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextReconciler.java

This extension in XtextReconciler would be tremendously useful for us, we need it to support lexical preprocessors.
The alternative for us is to copy most of the class, but then it becomes a burden for us every time we upgrade to a new version.

Allow override of getResourceText in XtextReconciler

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/Messages.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/messages.properties
org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java

The "Generic IDE Support"  option is disabled whenever a UI plugin is selected. If
it was not enabled before, it will be selected automatically and an
information about this will be reported to the status widget.
Initial page: "Generic IDE Support" is disabled, since Eclipse Plugin is preselected.
The option becomes enabled when Eclipse Plugin is deseleted.
The option is deselected manually:
The option "Web Support" is selected. The user is informed about the automatic selection of the "Generic IDE Support" option.

[#119] UX improvements for Generic IDE Support option

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Add org.eclipse.buildship.feature.group to the target platform in order to use Gradle tooling and Gradle classpath containers in runtime projects

Add Buildship to target platform

---

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccess2Test.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java

Don't call InputStream.reset() when it's not supported

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend
org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java

The creation of a p2 repository requires the SDK project. If not
selected before, the feature project is automatically selected and an
information message about the selection is presented.
When 'Eclipse plug-in' is deselected, also the feature and p2 projects
are deselected.
Select 'Create Update Site', 'Create Feature' is automatically selected:
Eclipse plug-in deselected, feature and p2 projects were selected before:

[#119] Auto (de) selection of Eclipse projects

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Generate locations.properties for use from gradle composite build. Helps to fix https://github.com/eclipse/xtext-umbrella/issues/18

Generate locations.properties for use from gradle composite build.

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

fixed #172: Install debug info into Java Byte Code for Xtend files

---

org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java
org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/editor/XbaseEditorInputRedirector.java
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/Arithmetics.xtext
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/validation/ArithmeticsValidator.xtend
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/xtend-gen/org/eclipse/xtext/example/arithmetics/validation/ArithmeticsValidator.java
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ide/build.properties
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/FormatterTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/ParserTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/FormatterTest.java
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/ParserTest.java
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/RuleEngine.xtext

Get rid of warnings in Examples.
Set BREE to Java 1.8
Fixes #164 and #174

Get rid of warnings in Examples.

---

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF

This is still the bundle containing classes for UI testing.
Closes #177
Task-Url: https://github.com/eclipse/xtext-extras/issues/177

177: Reintroduce dep to org.eclipse.xtext.junit4

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/GlobalURIEditorOpener.java

GlobalURIEditorOpener: Marked IWorkbench as @Nullable so that Xtext Languages can activate in a headless eclipse without workbench
Fixes #153 
Fixes [437425] 

GlobalURIEditorOpener: Marked IWorkbench as @Nullable

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseDispatchingEObjectTextHover.java

The XbaseDispatchingEObjectTextHover class does not reply the
XConstructorCall, but the JvmConstructor. This avoids to use Xbase hover
API (the JDT one is used).
This commit adds the support of XConstructorCall to the
XbaseDispatchingEObjectTextHover class.
Signed-off-by: Stéphane Galland <galland@arakhne.org>

Adding support of XConstructorCall into Xbase dispatching hover.

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/StratumBreakpointAdapterFactory.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/bracketmatching/GoToMatchingBracketAction.java

Change GoToMatchingBracketAction and StratumBreakpointAdapterFactory to
do cast to ITextSelection instead of TextSelection to allow editors wrap
TextSelection into some extended selection while still implementing
ITextSelection.
Signed-off-by: Roman Mitin <roman.mitin@gmail.com>

[#194] Cast to ITextSelection instead of TextSelection

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/autoedit/DefaultAutoEditStrategyProvider.java
org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/editor/autoedit/XtextAutoEditStrategyTest.java

fixed autoedit in copyright comments.
https://github.com/eclipse/xtext-xtend/issues/163

fixed autoedit in copyright comments.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Currently there was a mylyn bugzilla query only for Xtext, not for
Xtend.

Oomph: bugzilla query for Xtend bugs

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java

make consistent use of getResourceServiceProvider in BuilderParticipant

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/actions/OutlineWithEditorLinker.java

[477446] Added Null Guard to OutlineWithEditorLinker.findBestNode

[477446] Added Null Guard to OutlineWithEditorLinker.findBestNode

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/FindReferencesHandler.java

add null check to FindReferencesHandler.getQueryExecutor. Fixes #224

add null check to FindReferencesHandler.getQueryExecutor. Fixes #224

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/ImportingTypesProposalProvider.java

[431968] Fixed [imports] automatic insert of fully qualified name for types in same file

[431968] Fixed [imports] automatic insert of fully qualified name for types in same file

---

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/ClassFileBasedOpenerContributor.java

[468120] get rid of explicit jdt.ui dependency in ClassFileBasedOpenerContributor

[468120] get rid of explicit jdt.ui dependency in ClassFileBasedOpenerContributor

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextQuickAssistProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/XtextAnnotation.java

Fixes eclipse/xtext-core#124.
Behavior before this change:
* If there is at least one annotation left of the cursor position, choose the nearest one with respect to the start offset. Quick fixes are shown for all annotations with exactly same range as the chosen one.
* If there is at least one annotation right of the cursor position, choose the one with the smallest offset. Quick fixes are shown for all annotations with exactly same range as the chosen one.
Behavior after this change:
* If there is at least one annotation that includes the cursor position, quick fixes are shown for all annotations that include the cursor position.
* If there is at least one annotation left of the cursor position, choose the nearest one with respect to the end offset. Quick fixes are shown for all …

Improved XtextQuickAssistProcessor.getApplicableAnnotations(..)

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/XtextBuildConsolePageParticipant.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/StratumBreakpointAdapterFactory.java
org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java
org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditorErrorTickUpdater.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewer.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractContentProposalProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/DefaultFoldingStructureProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/occurrences/OccurrenceMarker.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/AbstractOutlineNode.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/AnnotationIssueProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DisplayChangeWrapper.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/tasks/preferences/TaskTagConfigurationBlock.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/FeatureProjectFactory.xtend
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverDocumentationProvider.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegate.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegateAdapterFactory.java

I had too many warnings in my workspace so I removed a few.
The pattern `(MyClass) getAdapter(MyClass.class);` was repeated so often I was wondering if we need this for backwards compatibility?!

Remove a few warnings

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/refactoring/DisplayChangeWrapperTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DisplayChangeWrapper.java

[477917] Fixed NullPointerException in DisplayChangeWrapper.getModifiedElement

[477917] Fixed NullPointerException in DisplayChangeWrapper.getModifiedElement

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/debug/JavaBreakPointProvider.java

[516391] Fixed NPE in JavaBreakPointProvider

[516391] Fixed NPE in JavaBreakPointProvider

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/preferences/BuilderConfigurationBlock.java

This function may be overridden by subtypes of `BuilderConfigurationBlock` in order to filter the output configurations that will be displayed in the preference/property pages.
Signed-off-by: Stéphane Galland <galland@arakhne.org>

Add getOutputConfiguration function in BuilderConfigurationBlock.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlinePage.java

Set redraw(false) before refreshing the treeviewer to avoid flickering.
Reset to redraw(true) after refresh.
Signed-off-by: HBuender <hendrik.buender@gmail.com>

[#278] OutlineView flickers on every Keystroke

---

releng/org.eclipse.xtext.contributor/Xtext.setup

The GEF release repository does not contain draw2d anymore. It was moved to the legacy repository. Oomph failed to set the target platform.

p2 repository url containing draw2d has changed

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorFactory.java

- Extend the EmbeddedEditorFactory.Builder API with the style(int)
method to be able to configure the SWT style of the embedded editor.

[#292] Add style(int) method to the EmbeddedEditorFactory.Builder API.

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/OrganizeImportsHandler.java

Don't do indentity edits during organize imports.
fixes eclipse/xtext-xtend#130

Don't do indentity edits during organize imports.

---

org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/Access.java
org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/Activator.java
org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/ExecutableExtensionFactory.java

When initialization fails during creation of the Guice injector, an
analysis of the installed bundles and versions is performed. This is
done to create a detailed error report which should help to identify the
issue.
Changed Access and ExecutableExtensionFactory to be better prepared to
the fact that the bundle was not properly started and injector might be
unavailable.
The error message could be for example:
```
Caused by: org.eclipse.core.runtime.CoreException: Xtext configuration error!
This error might indicate missing version constraints of installed Xtext based bundles.
The following bundles were detected that require Xtext UI:
- org.eclipse.emf.mwe2.language.ui 2.9.1.201706191249 [STARTING]
- org.xtext.example.mydsl.ui 1.0.0.qualifier [STARTING]
The installed Xtext bundle versions …
```

[475431] Provide better error reporting on initialization failure

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/ITraceForStorageProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/TraceForStorageProvider.java

EclipseResourceFileSystemAccess was injecting the implementation class
TraceForStorageProvider and could not inject the interface, since 2
methods on the implementation class were used that are not part of the
interface. For these methods ITraceForStorageProviderExtension was
created.
This allows disabling writing trace files by binding
ITraceForStorageProvider.Null (usually performance reason when no trace
is required).
Also cleaned up unused field `workspace`.

Bug#438625 [EclipseResourceFileSystemAccess2] fileBasedTraceInformation should be of type ITraceForStorageProvider

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java

fixed wrong treatment of ^ as first character in prefix for xbase proposals
https://github.com/eclipse/xtext-xtend/issues/242

fixed wrong treatment of ^ as first character in prefix for xbase proposals

---

org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/Activator.java

"Runtime bundle is NEWER than UI bundles" may be false positive #329

"Runtime bundle is NEWER than UI bundles" may be false positive #329

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/refactoring/XbaseReferenceUpdater.java

[473623] Xbase creates Imports when refactoring even if the language has no XImport Section Support

[473623] Xbase creates Imports when refactoring even if the language has no XImport Section Support

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/participant/ChangeConverter.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring/participant/ChangeConverter.java

...because text replacements are applied on the new URI

[Refactoring] do rename before text replacements

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/label/DefaultDescriptionLabelProvider.java

[xtext-eclipse] made DefaultDescriptionLabelProvider#image() dispatchable for EClass #85

[xtext-eclipse] made DefaultDescriptionLabelProvider#image() dispatchable for EClass #85

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AnnotationWithQuickFixesHover.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/QuickAssistCompletionProposal.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextQuickAssistProcessor.java

IAnnotationModel.getPosition() might return null. This would later lead
to invalid proposals with null position and to NPE when accessing them.
Also guarded arguments to QuickAssistCompletionProposal.

[472992] Add null guard when position could be retrieved for annotation

---

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java

The IAE might be thrown when the source is missing. By catching the
exception more details of the actual context is available by the thrown
ISE.
This does not resolve the cause, but will give a better message to the user and might help to handle the situation better in the future.

[465642] Handle IAE thrown by ASTNode#setSourceRange

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.java

* The way how priorities were handled was wrong because `createProposals` can be invoked multiple times with different contexts. The modified version retains the priorities computed by the IdeContentProposalProvider.
* Use `doCreateProposal` instead of `createCompletionProposal` so the validation of proposals is skipped. Validation can already be done in IdeContentProposalProvider, so we don't need to repeat it.
* Added empty implementations of `completeAssignment`, `completeKeyword`, and `completeRuleCall` to satisfy the abstract superclass (they are not used in this implementation).
* Added `getDisplayString(ContentAssistEntry)` with a default implementation that includes the `label` and the `description` properties.
* Added a default implementation for `getImage(ContentAssistEntry)` …

Improved UiToIdeContentProposalProvider

---

org.eclipse.xtext.xbase.ui.testing/src/org/eclipse/xtext/xbase/ui/testing/AbstractXbaseContentAssistTest.java

fixed content assist tests after changes to collection literals

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/CreateJavaTypeQuickfixes.java

[522425] prevent npe in CreateJavaTypeQuickfixes

[522425] prevent npe in CreateJavaTypeQuickfixes

---

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtTypeProvider.java

introduced property to make the support of secondary types skippable #360

introduced property to make the support of secondary types skippable #360

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Also made MPC optional since to available on Photon M2 and it is not a
mandatory feature for the development environment.

[#384] Add Photon to Xtext targlet's repository lists

---

releng/org.eclipse.xtext.contributor/Xtext.setup

- Enable usage of maintenance streams
- Removed FindBugs from Eclipse setup
- p2 URI variables
- Harmonized variable names
- Added URIs for Xtext releases & milestones
- Introduced variables for hard coded p2 URLs
- SWTBot, Xpand, Xtext Orbit, GEF, Draw2D, m2e, Webtools
- Maintenance Streams
- Renamed streams maintenance -> maintenance_2.11
- Removed xtext.git.branch variables
Implied by stream name and variable in main project config
- Removed obsolete EMF p2 URL variable overload
- Git branch for umbrella must be fixed 'master', not stream dependent
- Target Platform
- Removed all Target Platforms before Luna
- Use p2 URI variables
- Removed obsolete Eclipse Updates repository - implied by default
- Added Xpand requirements & repository
- Merged Targlet 'Xtext Tools' into 'Xtext Target …

Setup refactorings

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/quickoutline/ShowQuickOutlineActionHandler.java

Can be triggered by opening "Quick Outline" in an Xtend file through the quick access.

Fixed NPE in ShowQuickOutlineActionHandler

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/debug/XbaseBreakpointPropertyTester.java

[509630] Avoid NCDFE when o.e.jdt.debug is not present

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/resource/AbstractScopeResourceDescriptionsTest.java

Since the test asserts the contents of the "Index" (ClusteringBuilderState) and I don't see explicit invocation of the Eclipse Builder - maybe the test is flaky because autobuild *sometimes* is late.
It adds to the situation that multiple tests create test files with the same name and one test asserts that this file isn't in the index.
Anyway, this is just a guess, since I can't reproduce the failure locally.

Try to make falky test more robust

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java

NPE:
```
java.lang.NullPointerException
at org.eclipse.xtext.ui.refactoring2.ChangeConverter.findOpenEditor(ChangeConverter.java:259)
at org.eclipse.xtext.ui.refactoring2.ChangeConverter._handleReplacements(ChangeConverter.java:169)
at org.eclipse.xtext.ui.refactoring2.ChangeConverter.handleReplacements(ChangeConverter.java:264)
at org.eclipse.xtext.ui.refactoring2.ChangeConverter.doConvert(ChangeConverter.java:114)
at org.eclipse.xtext.ui.refactoring2.ChangeConverter.accept(ChangeConverter.java:99)
at org.eclipse.xtext.ui.refactoring2.ChangeConverter.accept(ChangeConverter.java:1)
at org.eclipse.xtext.ide.serializer.impl.RecordingXtextResourceUpdater.applyChange(RecordingXtextResourceUpdater.java:90)
at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.endRecordChanges(ChangeSerializ …
```

[RenameElementDialog] Fix NPE when refactoring runs in own thread.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/XtextMoveResourceParticipant.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/XtextRenameResourceParticipant.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/XtextMoveResourceParticipant.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/XtextRenameResourceParticipant.java

Text changes must...
- occur before file rename changes when part of a composite change
- use the pre-rename file name to load file contents.
Otherwise the Eclipse Refactoring Preview Dialog can not display a
Comparison View for the changes.

fixed #425 [RenameFileRefactoring] Exceptions in Preview Dialog

---

org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/ui/quickfix/QuickfixCrossrefTestLanguageQuickfixProvider.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/WorkbenchMarkerResolutionAdapter.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/quickfix/WorkbenchMarkerResolutionAdapter.java

This bug causes two marker resolutions being offered for the primary
marker. If the user doens't de-select it, the resolution for the primary
marker will be executed twice.

[QuickFix] #findOtherMarkers() must not return primary marker

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/XtextBuildConsolePageParticipant.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MockMarker.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewer.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/AbstractOutlineNode.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DisplayChangeWrapper.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverDocumentationProvider.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegate.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegateAdapterFactory.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/GrammarLinkingInWorkspaceTest.java

Removed several unnecessary @SuppressWarnings annotations and two unused
imports.
Signed-off-by: Florian Stolte <fstolte@itemis.de>

Refactoring: Cleaning up warnings

---

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java
org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/ui/quickfix/QuickfixCrossrefTestLanguageQuickfixProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditorErrorTickUpdater.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewer.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/DefaultFoldingStructureProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/occurrences/OccurrenceMarker.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/AnnotationIssueProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/tasks/preferences/TaskTagConfigurationBlock.java
org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/CompilationTestHelper.java
org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler.java
org.eclipse.xtext.xbase.junit/testdata/testdata/ClassWithVarArgs.java
org.eclipse.xtext.xbase.junit/testdata/testdata/ClosureClient.java
org.eclipse.xtext.xbase.junit/testdata/testdata/ClosureClient2.java
org.eclipse.xtext.xbase.junit/testdata/testdata/GenericType2.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverDocumentationProvider.java

Added several @SuppressWarnings("unchecked") and @SafeVarargs
annotations to get rid of unnecessary warnings.
Signed-off-by: Florian Stolte <fstolte@itemis.de>

Refactoring: Remove warnings

---

org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.xtend
org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler.java
org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/builder/XbaseBuilderPreferenceAccess.java

added support for java 9  https://github.com/eclipse/xtext-core/issues/500

added support for java 9 

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Projects have been moved to xtext-idea with eclipse/xtext-xtend#311

[releng] Removed project import exclusion for *.idea projects

---

releng/org.eclipse.xtext.contributor/Xtext.setup

This change offers a drop down box to select "Xtext Version" to use for
p2 install and target platform. The choice will influence the p2 repos
to use for Xtext,MWE,Xpand.
Added Xtext SDK to the target platform for the case that only a subset
of subprojects are installed and required bundles are added from the
target platform then.

[#489] Added choice to select Xtext version

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/resource/AbstractScopeResourceDescriptionsTest.java

PersistentStateScopeResourceDescriptionsTest fails on photon #494

PersistentStateScopeResourceDescriptionsTest fails on photon #494

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/outline/StringMatcherTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/quickoutline/StringMatcher.java

[528817] Fixed PatternSyntaxException below StringMatcher.getPattern

[528817] Fixed PatternSyntaxException below StringMatcher.getPattern

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/DontAskAgainDialogs.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/DontAskAgainPreferences.java

DontAskAgainDialogs allowed you to manage "Do not ask again" settings, but it always did this via a dialog. There are other ways to show this option to the user, thus I made the class more generic.
This also allows for more granular resets of such settings. Before, when you reset the DontAskAgain setting, all of them got reset. Now you can create two classes (e.g. XtendDontAskAgainPreferences and JavaDontAskAgainPrefences.) that both extend DontAskAgainPreferences. These would have two different prefixes, which allows for their settings to be cleared separately for each of them.
Signed-off-by: Titouan <titouan.vervack@sigasi.com>

Generalized DontAskAgain

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/handler/ValidateActionHandler.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/AddMarkersOperation.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/MarkerIssueProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/ValidatingEditorCallback.java

Xtext adds annotations when validating from the editor. These
annotations are set in addition to the ones based on resource markers.
If an expensive validation is triggered it is necessary to remove these
annotations as well to ensure that validations that are NOT triggered by
expensive validation are not shown (of course they will be re-added in
case the validation is triggered e.g. by an edit again).
Change-Id: I0b2708e8a24a54e382f8a6a809dc8883b99c8637

[#462] Remove annotations not based on resource markers.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/AnnotatedTextToString.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/util/AnnotatedTextToString.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java

Change-Id: I3bc38ee1d402026d4f304dca6c618623bf80e5a1

[#514] Fix tests under windows by handling \r\n as well as \n.

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java

Experimented with highlighting while open/close outline view, setting
breakpoints etc. Can not find any side effect when removing the
"forceReconcile()" call. I guess the original bug 454227 was fixed by
the other changes inside
https://github.com/eclipse/xtext-eclipse/commit/d4fe755d6dd211ce0ca0d498d3f9e5913d4659e6
and the added "forceReconcile()" was a mistake. After removing the call
no duplicate highlighting happens any more. This should improve
performance for large files or files with expensive semantic
highlighting quite a lot.
Change-Id: I3a543dfa1f0e7b1e690bf40fbf1db766c73217b5

[#347] Avoid double semantic highlighting by removing bad call.

---

org.eclipse.xtext.common.types.shared/src/org/eclipse/xtext/common/types/shared/SharedCommonTypesModule.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/DefaultUiModule.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/copyqualifiedname/AbstractCopyQualifiedNameHandler.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/copyqualifiedname/CopyQualifiedNameService.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/copyqualifiedname/DefaultCopyQualifiedNameService.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/copyqualifiedname/CopyQualifiedNameService.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/copyqualifiedname/DefaultCopyQualifiedNameService.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XbaseUiModule.xtend
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/copyqualifiedname/XbaseCopyQualifiedNameService.xtend
org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/XbaseUiModule.java
org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/editor/copyqualifiedname/XbaseCopyQualifiedNameService.java

Change implementation to use new classesfrom xtext core plugin and
deprecate the UI classes.
Change-Id: I0d3faf0b96e967bf95c549c9e82749e95c24c1c1

[xtext-eclipse#145] Extend implementations from core.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

- removed target "Oxygen Staging"
- replaced target "Photon Staging" by "Photon Integration"
- renamed variable p2.xtext.orbit => p2.orbit
- changed Orbit URL to Photon M5 stable (for asm 6)
- added org.objectweb.asm and org.objectweb.asm.tree [6,7) to target
platform
- changed default target platform to Oxygen

[#527] Oomph setup changed

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml

Configure profiles for Mac and JDK9+ and configure tycho-surefire-plugin
dependent on activated profiles.

[eclipse/xtext#623] Enable to build on JDK 9

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java

[#525] added missing disablement for emf notifications during clearing of resourcesets

[#525] added missing disablement for emf notifications during clearing of resourcesets

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/SyncUtil.java

I Have no way of reproducing this but there are plenty of nullchecks on ValidationJob in other places.

Fixed NPE in SyncUtil

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/GlobalURIEditorOpener.java

Happens when you try to open an URI with an empty fragment i.e. a file.

Fixed NPE when opening an uri with empty fragment

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/DebugSourceInstallingCompilationParticipant.java

This will remove the dependency on `org.eclipse.jdt.internal.core.Region`.

[#552] Resolve usage of internal class Region

---

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractBuilderParticipantTest.java

[#560] Restore old Delegate on TearDown so that other tests are not affected

[#560] Restore old Delegate on TearDown so that other tests are not affected

---

org.eclipse.xtext.xbase.ui.tests/src-longrunning/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistInBlockTest.java

[#565] made content assist test order independent

[#565] made content assist test order independent

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java

Editors should remain unsaved after a refactoring only when no persited
files are affected. Otherwise, the builder will find an inconsistent
state since it can't see the dirty state.

[Refactoring] Save editors when persisted files are affected

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/EditorDocumentChange.java

use case: persisted files should be in a consistent state after
refactoring and quickfix-operations. Thus, if some of those files are
opened in an editor, we currently modify the editor's contents and save
if afterwards (see https://github.com/eclipse/xtext-eclipse/pull/593 )
However, running editor.save() in Display.syncExec() seems to make the
file changes escape the workspace modification operations. Consequently,
the builder running after the operations doens't see all changes.
This change attempts to make editor.save() and TextEdit.apply() runnable
in non-display-thread, so that refactoring and quickfix operations can
safely be executed in non-display-threads and don't escape
workspace-operations.

[xtexteditor] support save() and rewrite() on non-display-thread

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/DefaultTextEditComposer.java

[eclipse/xtext-core#449] Avoid stack overflow with deep EMF containment

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/contentassist/XtextContentAssistTest.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/contentassist/XtextProposalProvider.java

In XtextProposalProvider#completeAssignment_Feature, an NPE can occur if the grammar contains a rule without type. Since there is a check if the eClassifier of the type is an EClass, is seems reasonable to also add a nullguard for the type to that if-statement.
This solution expects that a grammar may contain a rule with getType() == null. If this is the case, it fixes #479. If such a rule is invalid, however, further investigation is neccesary to find the root cause for that issue.
Signed-off-by: Florian Stolte <fstolte@gmx.de>

[#479] Prevent NPE in XtextProposalProvider if rule has no type.

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/contentassist/XtextProposalProvider.java

In `XtextProposalProvider#isProposeParserRule`, an NPE can occur if the grammar contains a rule without type. Since rules without types cannot possibly match the `eClassifier` parameter of the method, they can safely be filtered out.
This solution expects that a grammar may contain a rule with `getType() == null`. If this is the case, it fixes #477. If such a rule is invalid, further investigation is neccesary to find the root cause for that issue.
Signed-off-by: Florian Stolte <fstolte@gmx.de>

[#477] Prevent NPE in XtextProposalProvider for rules without type.

---

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/xtext/ui/ContentAssistTest.java

[#607] Made ContentAssistTest work with Multiple Guava Versions

[#607] Made ContentAssistTest work with Multiple Guava Versions

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringExecuter.java

Because this freezes the UI.
Also, don't call yieldToQueuedDisplayJobs() because we're inside a
Workspace Operation and this causes the Resource Change Events to be
handled prematurely and thus to *not* trigger a build.

[refactoring] don't run build in UI thread

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/contentassist/XtextContentAssistTest.java

[eclipse/xtext-core#664] Fixed Content Assist Tests regarding new grammar annotations

[eclipse/xtext-core#664] Fixed Content Assist Tests regarding new grammar annotations

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/formatting/StatemachineFormatter.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/formatting/StatemachineFormatter.java

See also https://github.com/eclipse/xtext-extras/issues/70

[NONE] Fix broken link in StatemachineFormatter of the fowlerdsl example

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectFactory.java

[eclipse/xtext-eclipse#626] fixed java project factory referencedProjects bug

[eclipse/xtext-eclipse#626] fixed java project factory referencedProjects bug

---

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.xtend

[NONE] Fix indentation in the formatter of the homeautomation example.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/PluginProjectFactory.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/Messages.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/WizardNewXtextProjectCreationPage.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/messages.properties
org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java

Fix case where unsupported JDK is added to the selection combo in case
it is selected as a default. Instead, in the unlikely case that the
default JDK is not supported, the last JDK from the list is selected.
Remove IDEA from the new project wizard. IDE plugins are not well
maintained any more, no need to bother new users with not working stuff.
Adding "Automatic-Module-Name" to manifest if selected java version is
at least 1.8.

[eclipse/xtext-core#686] Update new project wizard.

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/generator/StatemachineGenerator.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/generator/StatemachineGenerator.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/jvmmodel/RuleEngineJvmModelInferrer.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/xtend-gen/org/eclipse/xtext/example/homeautomation/jvmmodel/RuleEngineJvmModelInferrer.java

- Modify the Generators of the Xtext Homeautomation and the Xtext
State-Machine examples to generate java classes with upper case letters.

[#631] Example generators java classes with upper case letter.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java

This is based on feedback of #617
It also needs https://github.com/eclipse/xtext-core/pull/682

Added I[Read|Write]Access and Priority to XtextDocumentLocker

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java
org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java

Resolves name ambiguity compile warning

Rename getJUnitVersion => getSelectedJUnitVersion

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AbstractProblemHoverTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AbstractProblemHover.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AnnotationWithQuickFixesHover.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/ProblemAnnotationHover.java

Fixes #649.
* `AbstractProblemHover.getAnnotations(int, int)` now returns all annotations that include the given offset (if it is ≥ 0). Those that match the given line number are put first in the list so consumers of that method will favor them over annotations that start on preceding lines.
* `ProblemAnnotationHover` and `AnnotationWithQuickFixesHover` further sort the list of annotations such that they first consider errors, then warnings, then the rest.

Improved filtering of annotations for hover

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.xtend
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.java

AbstractEditorDoubleClickTextSelectionTest abstract class to provide a
base infrastructure for testing a customized DoubleClickStrategyProvider
behaviour.

[#654] Add AbstractEditorDoubleClickTextSelectionTest abstract class.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Bundles required by
xtext-umbrella/releng/org.eclipse.xtext.releng.simrel.tests:
- org.eclipse.cbi.p2repo.analyzers
- org.eclipse.cbi.p2repo.analyzers.common
Making these bundles optional, since repositories are only available for
Neon+.

[eclipse/xtext-umbrella#60] Add CBI Analyzer to modular target

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/ParallelBuilderParticipant.java

Typo in method name. Added getParallelFileSystemAccess as replacement.

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.java

It looks as if the test runner thread is interrupted. I can't say why.
The test is failing after only 4ms of execution time. Looks like the
test thread is interrupted at the start of the method already. It might
be that we are bitten by a JUnit bug here: junit-team/junit4#1365
Insert a "Thread.currentThread.interrupted" at the start of the test
case to ensure the interrupted flag is cleared.

[#681] Clear interrupted state of test tread at start of method.

---

releng/org.eclipse.xtext.contributor/Xtext.setup
releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1178] bootstrap against 2.14

[eclipse/xtext#1178] bootstrap against 2.14

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextDocumentReconcileStrategy.java

Printing source code is not always something that is acceptable thus there should be a way to disable this behaviour. Extracting the message creation to an overridable function achieves this purpose.

Made printing of source code on error overridable

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/EditorResourceAccess.java

I have no way to reproduce this but you can find a stacktrace we encountered below
```
Unhandled event loop exception
java.lang.NullPointerException
at org.eclipse.xtext.ui.editor.findrefs.EditorResourceAccess$1.exec(EditorResourceAccess.java:37)
at org.eclipse.xtext.ui.editor.findrefs.EditorResourceAccess$1.exec(EditorResourceAccess.java:1)
at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
at org.eclipse.xtext.ui.editor.findrefs.EditorResourceAccess.readOnly( …
```

Fixed possible NPE

---

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/BuilderParticipantTest.java

[eclipse/xtext-eclipse#681] fixed test not resetting its state

[eclipse/xtext-eclipse#681] fixed test not resetting its state

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/PersistentDataAwareDirtyResource.java

You can just close this ticket if you don't think it's worth deprecating these methods for the typo. Whatever the response, I'll keep it in mind for future contributions.

Fixed typo in PersistentDataAwareDirtyResource

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java

Since the refactoring applies content changes before applying move
changes, the content changes must be applied to the old URI.

Bugfix related to move refactoring of non-Xtext resources

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/AbstractOutlineNode.java

This can happen when the `getEObjectURI()` is out of sync with the XtextResource.
It occurred to me in the `getChildren()` call when I was adding a new element to my file and then pressing Ctrl+Z at exactly the right time. This made the `getEObjectURI()` return the new element, but it was queried on an XtextResource that no longer had said item.
Of course you can fix this in your implementation by adding a dispatch for `getChildren()` that handles `Void` items, but this would have to be done for every outline implementation and it doesn't seem useful to me at all to try to create an outline node for a null item.
This PR needs API from https://github.com/eclipse/xtext-core/pull/766.

Prevent NPE in outlines when eObject is null

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/preferences/BuilderConfigurationBlock.java

- Ensure that output configuration table widget expands horizontally
over all the 3 columns and not only resides in the first column.

https://github.com/eclipse/xtext-xtend/issues/459

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/src/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/formatting2/StatemachineFormatter.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/formatting2/StatemachineFormatter.java

- Ensure that the formatter inserts an empty line between the events and
the commands block (if no resetEvents block), between the events and the
states block (if no resetEvents block and or commands block), and
between the resetEvents and the states block (if no commands block).
- Implement corresponding StatemachineFormatterTest test cases.

[#699] Improve the Formatter of the Xtext State-Machine Example.

---

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.java

- Use the FileExtensionProvider.primaryFileExtension method to access
the file extension instead of using the hard-coded '.rules' literal.

Improve the SerializerTest of the Xtext Homeautomation Example.

---

org.eclipse.xtext.xtext.ui.examples/plugin.properties
org.eclipse.xtext.xtext.ui.examples/plugin.xml

- Move the description text from the plugin.xml into the
plugin.properties to eliminate the usage of duplicated text literals.

Extract the Xtext Example plugin descriptions to the plugin.properties.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectFactory.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java

- Support output folders per source fodler
- Support test source folder

[eclipse/xtext-eclipse#677] Additional source folder support.

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ide/.classpath
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/.classpath
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/.classpath
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/.classpath
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/.classpath
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ide/.classpath

- Modify the .classpath files to contain the source folders in the
following order: src, src-gen, xtend-gen.

Sort the source folders of the Xtext Example projects.

---

org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/OutputConfiguration.java

[eclipse/xtext-maven#30] add support for missing keepLocalHistory and setDerivedProperty options

[eclipse/xtext-maven#30] add support for missing keepLocalHistory and setDerivedProperty options

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/scoping/namespaces/JavaProjectsStateTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/scoping/namespaces/StrictJavaProjectsStateTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/containers/AbstractJavaProjectsState.java

#740 made JavaProjectState better testable and fixed npe in tests

made JavaProjectState better testable and fixed npe in tests

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AbstractCompositeHoverTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AbstractProblemHoverTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AnnotationWithQuickFixesHoverTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/DispatchingEObjectTextHoverTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/ProblemHoverTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/html/XtextElementLinksTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/outline/AbstractOutlineWorkbenchTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/LinkingErrorTest.java

[#739] Avoid double closing of editors

[#739] Avoid double closing of editors

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.java

AbstractHighlightingTest abstract class to provide a base infrastructure
for testing the (customized) syntactical/semantical highlighting
behaviour.
- Extend the State-Machine Xtext example by the
StatemachineHighlightingTest to demonstrate the usage of the
AbstractHighlightingTest test class.

[#736] Add syntactical/semantical highlighting ui test infrastructure.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/doubleClicking/AbstractWordAwareDoubleClickStrategy.java

[eclipse/xtext-eclipse#759] made AbstractWordAwareDoubleClickStrategy compatible with newer ICU versions

[eclipse/xtext-eclipse#759] made AbstractWordAwareDoubleClickStrategy compatible with newer ICU versions

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml

fix mwe range that breaks once the 2.9.2 snapshot will be available

fix mwe range that breaks once the 2.9.2 snapshot will be available

---

org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/ui/quickfix/QuickfixCrossrefTestLanguageQuickfixProvider.java
org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/validation/QuickfixCrossrefTestLanguageValidator.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java

More tests for QuickFixes that don't update CrossRefs.

---

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/TargetPlatformUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/TargetPlatformUtil.java

[#772] Don't do anything in TargetPlatformUtil when called from eclipse pde

[#772] Don't do anything in TargetPlatformUtil when called from eclipse pde

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/TargetURIConverter.java

marked old TargetURIConverter as deprecated

marked old TargetURIConverter as deprecated

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverDocumentationProvider.java

[eclipse/xtext-eclipse#782] fixed javadoc links in javadoc of types. fixed javadoc links to constructors

[eclipse/xtext-eclipse#782] fixed javadoc links in javadoc of types. fixed javadoc links to constructors

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegateJunitLaunch.java

- Modify the JavaElementDelegateJunitLaunch to consider the type
hierarchy (inherited test methods) by determining if an Xtend file
contains a JUnit test method.

[#768] Ensure that the Run As -> JUnit Test occurs on inherited tests.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd

[eclipse/xtext-core#824] remove superfluous dependency to xpand

[eclipse/xtext-core#824] remove superfluous dependency to xpand

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/DontAskAgainPreferences.java

Usually comparing to a constant is the way.
However, we're comparing to a String that's being pulled from an on disk preference file thus it will obviously not be the same instance as the constant.

Fixed bad equals in DontAskAgainPreferences

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/quickfix/StatemachineQuickfixProvider.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/quickfix/StatemachineQuickfixProvider.java

- Change the methode name from 'capitalizeName' to
'convertNameToFirstLowerCase' to better indicate what the quickfix does.

State-Machine Example QuickfixProvider - Use more meaningful method name.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java

Comment is based on org.eclipse.ui.texteditor.AbstractTextEditor.getSourceViewer().
Is it to specific on that interface? If so, what would be better? It can definitely be null

Added comment about possible null return

---

Jenkinsfile
releng/org.eclipse.xtext.tycho.parent/pom.xml

Build steps defined in Jenkinsfile pass the built-in environment
variable 'JENKINS_URL' to the Gradle/Maven executions. This is evaluated
in the build scripts for upstream repository URLs. On Xtext JIPP this
will use upstream repos from JIPP. In local builds outside of Jenkins
the property defaults to Typefox CI like before.

[eclipse/xtext#1224] Detect local Jenkins environment

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/RealXtextDocumentModifyTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/IXtextModelListener.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java

Some of the IXtextModelListeners silently assume that the IDocument that
is associated with the XtextResource is not being changed during the
listener's run.  This patch achieves this by running the
IXtextModelListeners on the UI thread.
eclipse/xtext-eclipse#816

Run IXtextModelListeners on the UI thread

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/ResourceForIEditorInputFactory.java

This allows to enable validation based on a URI instead of having to override the entire `createResource(URI)` method. This already existed for `createResource(IStorage)`

Add API to override validation disable for external files

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/.classpath

- Make the Formatter2 API classes accessible by defining an explicit
access rule on the org.eclipse.xtext.formatting2 package.

Xtext State-Machine Example: Eliminate discouragedReference warnings.

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

- use xtend-maven-plugin 2.15
- remove signature workaround

[eclipse/xtext#1272] Xtext bootstrap 2.15

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/quickfix/QuickfixTest.java

AbstractQuickfixTest abstract class to provide a base infrastructure for
testing quickfixes.
- Extend the Xtext Simple Arithmetics example by the QuickfixTest to
demonstrate the usage of the AbstractQuickfixTest class.

[#839] Provide AbstractQuickfixTest abstract base class.

---

org.eclipse.xtext.ui.codemining/src/org/eclipse/xtext/ui/codemining/AbstractXtextCodeMiningProvider.java

- Modify the AbstractXtextCodeMiningProvider to set not only the offset,
but also the length of the Position object.

[#836] Ensure the CodeMining works on 2018-09.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineQuickfixTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineQuickfixTest.java

- The Domainmodel/Homeautomation QuickfixTest demonstrate the usage of
the AbstractQuickfixTest base class in combination with Xbase languages
that require java project.

[#839] Add QuickfixTest to the Xtext Domainmodel/Homeautomation example.

---

org.eclipse.xtext.ui.codemining/src/org/eclipse/xtext/ui/codemining/AbstractXtextCodeMiningProvider.java

- Set the lenght of a Position object to '1' instead of the lenght of
the content text.

[#836] Provide better fix for CodeMining functionality bug on Photon.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/IRefactoringUpdateAcceptor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/EmfResourceChangeUtil.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/RefactoringUpdateAcceptor.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/MultiImportOrganizer.java

`IRefactoringDocument.Provider.get()` can produce null values but none of the callers do any null checks

Prevent NPE when RefactoringDocument is null

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1321] bootstrap against 2.16.0.M1

[eclipse/xtext#1321] bootstrap against 2.16.0.M1

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseDispatchingEObjectTextHover.java

- Extend the XbaseDispatchingEObjectTextHover to provide hover
information on types referenced in javadoc comments.

https://github.com/eclipse/xtext-xtend/issues/372 Hover in javadoc.

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseDispatchingEObjectTextHover.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/navigation/XbaseHyperLinkHelper.java

- Eliminate duplicated code in the Javadoc hovering/hyperlinking
functionality by introducing the JavaDocHelper utility class.

https://github.com/eclipse/xtext-xtend/issues/372 Refactoring.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.java

- Modify the AbstractQuickfixTest to use the IResourceSetProvider to
obtain a new resource while testing the IssueModification effect.
- Implement corresponding QuickfixTest DomainModel Example test cases.

[#839] Ensure the Xbase organize import quickfix can be properly tested.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHoverTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHoverTest.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/hover/HoverTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/hover/HoverTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHoverTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHoverTest.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHoverTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHoverTest.java

AbstractHoverTest abstract class to provide a base infrastructure for
testing hovers.
- Extend the Xtext Examples the HoverTest test cases to
demonstrate the usage of the AbstractHoverTest class.

[#897] Provide AbstractHoverTest abstract base class.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectFactory.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/PluginProjectFactory.java

To avoid an NPE clients should use the getter getFolders().

[#902] Avoid NPE on accessing 'folders' field

---

org.eclipse.xtext.xtext.ui.examples/pom.xml

[#907] fixed broken cleaning and packaging of xtext example projects

[#907] fixed broken cleaning and packaging of xtext example projects

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/templates/XtextTemplateContext.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/templates/XtextTemplateContextTest.java

- Use IndentationAwareTemplateTranslator even for empty document
- Fix Use IndentationAwareTemplateTranslator such that line ending from
system is used (instead of line ending taken from template).

#755 Fix failing UI tests in domain model example.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/ContentProposalPriorities.java

Just a quick proposal for adjusting the behavior described in #917.
Please feel free to close without merge if you feel this doesn't make sense!

[#917] do not punish perfectly matching content assist proposals

---

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/ResourceDescriptionUpdaterTest.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractParticipatingBuilderTest.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug355821Test.java

Because multiple threads (main + build thread) may access state
concurrently.

#796 Make AbstractParticipatingBuilderTest thread safe

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1382] Bootstrap against 2.17.0.M1

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java

[eclipse/xtext-xtend#677] Eclipse Xtend favorites: fixed empty case for preference

[eclipse/xtext-xtend#677] Eclipse Xtend favorites: fixed empty case for preference

---

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/JavaVersionExtendedTest.java

[eclipse/xtext#1182] added support for java 11 as target

[eclipse/xtext#1182] added support for java 11 as target

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/hyperlinking/HyperlinkingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/hyperlinking/HyperlinkingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HyperlinkingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/HyperlinkingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHyperlinkingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHyperlinkingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHyperlinkingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHyperlinkingTest.java

AbstractHyperlinkingTest abstract class to provide a base infrastructure
for testing hyperlink navigations.
- Extend the Xtext Examples the HyperlinkingTest test cases to
demonstrate the usage of the AbstractHyperlinkingTest class.

[#949] Provide the AbstractHyperlinkingTest abstract base class.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/TokenScanner.java

Bug can be reproduced by e.g. doing <right-click> --> Compare with HEAD
revision on an xtend file in a Git repo.
Or select one xtext document and a non-xtext document and do a compare.
Signed-off-by: Anders Dahlberg <anders.xb.dahlberg@ericsson.com>

Fix ClassCastException in Compare View.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HyperlinkingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/HyperlinkingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/navigation/DomainmodelHyperlinkHelper.java

- Modify the DomainmodelHyperlinkHelper to recognize hyperlinks in
javadocs.
- Implement corresponding HyperlinkingTest test cases.

[#951] Extend the Domainmodel Example by hyperlinking in javadoc.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.xtend
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractEditorTest.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHoverTest.xtend
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.xtend
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.java
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.java
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHoverTest.java
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.java
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/occurrences/MarkOccurrencesTest.java
org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend
org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.java

- Modify the AbstractEditorTest class to provide a default
implementation of the getEditorId() method instead of being an abstract
method.
- Eliminate the getEditorId() method from the derived classes that
provide the same implementation of the getEditorId() method as the
inherited one.

Refactoring the Xtext UI Test Infrastructure.

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java
org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend
org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java

- Ensure that the IResourcesSetupUtil.cleanWorkspace() method is called
only once after each test execution. The call is already triggered by
the inherited AbstractWorkbenchTest.tearDown() method, so there is no
need to trigger it once again from the concrete test cases.

Speed up the Xtext UI Test cases.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/navigation/DomainmodelHyperlinkHelper.java

- Use the inherited EObjectAtOffsetHelper instance instead of injecting
an own one.

Refactoring the DomainmodelHyperlinkHelper in the Domain-Model Example.

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java

- Use the same layout in the XtextGrammarQuickfixTest as in the
ValidationIssue719QuickFixTest to improve consistency and readability.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=410479

[#410479] Refactoring the XtextGrammarQuickfixTest test cases.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/XtextProjectHelper.java

Although happened in a misconfigured project it would be better to guard this instead of throwing NPE.

Add null guards

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1405] bootstrap against 2.17.0

[eclipse/xtext#1405] bootstrap against 2.17.0

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HighlightingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/HighlightingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.java

- Modify the AbstractHighlightingTest to properly wait for the semantic
highlighting to be completed before asserting the result.
- Modify the AbstractHighlightingTest to be more extensible by clients.
- Add corresponding DomainmodelHighlightingTest,
RuleEngineHighlightingTest, StatemachineHighlightingTest test cases.

[#980] Ensure the AbstractHighlightingTest works properly.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml

[#991] removed duplicate entry in maven clean plugin config

[#991] removed duplicate entry in maven clean plugin config

---

README.md
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
releng/org.eclipse.xtext.tycho.parent/pom.xml

Use https://ci.eclipse.org/xtext as default Jenkins URL

[eclipse/xtext#1424] Change default Jenkins

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.java

… in favor of proper memory deallocation, addresses #1048

refactoring2: improved handling of 'IChangeSerializer' instance in 'ResourceRelocationProcessor'

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.xtend
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/ProgressReportingTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.java
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/refactoring/ProgressReportingTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.java

… as demanded in #1053;
added corresponding test (`ProgressReportingTest`).

[refactoring] fixed progress reporting of rename+move refactorings in 'ResourceRelocationProcessor'

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlinePage.java

1. Open an Xtend editor
2. Open the outline view
3. Type something in the Xtend editor such that the outline refreshes
4. After typing quickly press (and hold) shift and tap the left arrow button to start selecting text
5. Note how the selection jumps around resulting in the last few characters not being selected
I don't really see why the outline would like to change the `SourceViewer`'s selection when it refreshes but feel free to let me know if I'm missing something

Prevent glitchy outline select

---

org.eclipse.xtext.junit4.tests/src/org/eclipse/xtext/junit4/DiagnosticTreeIterableTest.java
org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/validation/AssertableDiagnostics.java

DiagnosticTreeIterator always returns the same iterator when you call
iterator(). This means it can't be iterated twice.
The `Iterable` interface does not force you to return a new `Iterator` every time but this is common practice. If this change doesn't get accepted because of this reason, it would be nice to at least have a comment on `iterator()`.

Make DiagnosticTreeIterator return a new iterator every time

---

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/smoketest/internal/WrappingInjectorProvider.java

[eclipse/xtext-core#1149] Apply proper restore logic also to SmokeTest infra

[eclipse/xtext-core#1149] Apply proper restore logic also to SmokeTest infra

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1473] bootstrap against 2.18

[eclipse/xtext#1473] bootstrap against 2.18

---

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccessTest.java
org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/MockJavaProjectProvider.java
org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/ui/refactoring/participant/TextChangeCombinerTest.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/autoedit/AutoEditTest.java
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/autoedit/Bug330096Test.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/encoding/EncodingTest.java
org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/editor/autoedit/XtextAutoEditStrategyTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java

- Eliminate duplicated code by reusing the
org.eclipse.xtext.ui.testing.util.IResourcesSetupUtil.root() helper
method whenever the test cases need access to the workspace root.

Refactoring the test case accesses the workspace root.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/IssueResolutionAcceptor.java

- Use the IModification interface instead of the concrete classes when
declaring the wrapper objects.

Refactoring in xtext.ui.editor.quickfix.IssueResolutionAcceptor class.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractFoldingTest.xtend
org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractFoldingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/folding/FoldingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/folding/FoldingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/FoldingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/FoldingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineFoldingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineFoldingTest.java

AbstractFoldingTest abstract class to provide a base infrastructure
for testing the folding capabilities.
- Extend the Xtext Examples the FoldingTest test cases to
demonstrate the usage of the AbstractFoldingTest class.

[#1096] Provide the AbstractFoldingTest abstract base class.

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/StatemachineUiModule.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/folding/StatemachineFoldingRegionProvider.xtend
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/StatemachineUiModule.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/folding/StatemachineFoldingRegionProvider.java

- Provide the StatemachineFoldingRegionProvider custom class that
computes folding regions not only for the states, but also for the
events, resetEvent and commands blocks.
- Provide corresponding binding in the StatemachineUiModule.
- Provide corresponding StatemachineFoldingTest UI test cases.

[#1103] Extend the Statemachine Xtext Editor folding capabilities.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

On current Eclipse installations Buildship 3.x is already picked from
the Eclipse SimRel repository. Current Buildship 3.1.0 is installable
also on Eclipse Oxygen, so changing the Buildship repository URL allows
to use the same Buildship version on Eclipse 4.7 and above.

[eclipse/xtext#1459] Change p2.buildship value to use Buildship 3.x

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/StatusWidget.xtend
org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/StatusWidget.java

- Adapt layout data of the StatusWidget to ensure that the
warnings/errors are properly displayed on the Advanced Page of the New
Xtext Project Wizard.

[#1108] Ensure warnings/errors are properly displayed on the Wizard page

---

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/TemporaryFolder.java

[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorFactory.java

Extend the EmbeddedEditorFactory by an API to be able to customize the
foreground/background colors of the line numbers column.

[#1126] Extend the EmbeddedEditorFactory by linenumbers colors API.

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1509] Bootstrap against 2.19.0.M1

[eclipse/xtext#1509] Bootstrap against 2.19.0.M1

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
releng/org.eclipse.xtext.contributor/Xtext.setup
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target

[eclipse/xtext#1279] use orbit simrel alias directly

[eclipse/xtext#1279] use orbit simrel alias directly

---

org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/hierarchy/DeferredHierarchyBuilder.java

[eclipse/xtext-lib#224] Stable method order when using Delegate annotation

[eclipse/xtext-lib#224] Stable method order when using Delegate

---

org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuildCancellationTest.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/IntegrationTest.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/SimpleProjectsIntegrationTest.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/IToBeBuiltComputerContribution.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ToBeBuiltComputer.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/JdtToBeBuiltComputer.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/ProjectClasspathChangeListener.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/SimpleProjectDependencyGraph.java
org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/NameBasedEObjectDescription.java
org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/SharedContributionWithJDT.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/TestedWorkspaceWithJDT.java

[#281] Improved interaction between Xtext builder and JDT

[#281] Improved interaction between Xtext builder and JDT

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1537] bootstrap against 2.19.0

[eclipse/xtext#1537] bootstrap against 2.19.0

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1538] use eclipse 2019-12 in target

[eclipse/xtext#1538] use eclipse 2019-12 in target

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/templates/templates.xml

- Use correct the whitespaces in the template.xml file.
- Adapt the corresponding ContentAssistTest test cases.

[#1192] Domainmodel Example: Harmozie whitespaces in template proposals.

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/autoedit/AutoEditTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/autoedit/AutoEditTest.java

- Eliminate unnecessary getEditorId() method that does the same as the
super implementation.
- This PR is an appendum to https://github.com/eclipse/xtext-eclipse/commit/ae7f9b8f2b9a7a92bce352ab79baf106fd0c4035#diff-c376f0d7106ef132b9b489fd869fddf1

Xtext Arithmetics Example: Clean up AutoEditTest.

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/META-INF/MANIFEST.MF

- Sort the exported packages lexicographically ascending in the
MANIFEST.MF file to ensure that the packages are shown in the same order
on the MANIFEST.MF editor page as on the Runtime editor page.

Xtext Examples: Clean up the Export-Package section of the MANIFEST.MF

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/IssueCodes.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java

- Add checkPropertyNamesAreUnique check to the DomainmodelValidator
class.
- Add DUPLICATE_PROPETY to the IssueCodes.
- Implement corresponding ValidationTests test cases.

[#1202] Domainmodel example: Add duplicated property validation rule.

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#1560] bootstrap against 2.20.0.M1

[eclipse/xtext#1560] bootstrap against 2.20.0.M1

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/labeling/DomainmodelLabelProvider.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/outline/DomainmodelOutlineTreeProvider.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/labeling/DomainmodelLabelProvider.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/outline/DomainmodelOutlineTreeProvider.java

- Modify the implementation of the DomainmodelLabelProvider and the
DomainmodelOutlineTreeProvider to not to create any outline view nodes
for the Jvm Parameterized Type Reference elements, to use B extends
LinkedList<String> text instead of the B label, to use styled String
after the : similar to Xtend.
- Implement corresponding OutlineTest test cases.

[#1217] Domainmodel example: Outline view improvements.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractOutlineTest.java

- Eliminate unnecessary override protected getEditorId() method.
This PR is an appendum to commit https://github.com/eclipse/xtext-eclipse/commit/ae7f9b8f2b9a7a92bce352ab79baf106fd0c4035

Update javadoc of the AbstractOutlineTest class.

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/META-INF/MANIFEST.MF

- Sort the 'Require-Bundle' entries lexicographically ascending to
enable a better comparison between them.

Cleaning up the Xtext Examples MANIFEST.MF files.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractFileTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/FileTemplate.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/ProjectTemplate.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateVariable.xtend
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/BooleanTemplateVariable.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/ContainerTemplateVariable.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/FileTemplate.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/GroupTemplateVariable.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/ProjectTemplate.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/StringSelectionTemplateVariable.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/StringTemplateVariable.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateVariable.java

- Fixing typos in the documentation.
- Formating source code.

Cleaning up the org.eclipse.xtext.ui.wizard.template package.

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/plugin.xml

- Align the plugin.xml file to the plugin.xml_gen file to get a better
diff when comparing them.

Xtext Domainmodel Example: format plugin.xml file.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/Messages.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResult.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultEvents.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewPage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewPageActions.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewTreeNode.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/messages.properties

The Find-References page now shows number of matches as a suffix in the
label that describes the search result.
The label is refreshed when the search finished - not after every single
hit was added to search result to avoid extensive redraws.
Signed-off-by: Mathias Rieder <mathias.rieder@gmail.com>

[eclipse/xtext#1425] show number of matches in ReferenceSearchViewPage

---

org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/ListenerRegistrar.java

Moved recovery build trigger to workspace job to avoid Eclipse start-up hang
Signed-off-by: Simeon Andreev <simeon.danailov.andreev@gmail.com>

[eclipse/xtext#1129] Moved recovery build trigger to job to avoid start-up hang

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

avoid 'Directory is empty. Can't process' warning

avoid 'Directory is empty. Can't process' warning

---

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/plugin.xml
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/GenerateStatemachine.mwe2

- Modify the projectWizard/fileWizard section of the
GenerateStatemachine.mwe2 workflow to generate new project wizard/new
file wizard buttons on the toolbar.
- Merge plugin.xml_gen into the plugin.xml.

[#1229] Xtext Statemachine Example: add wizard generateToolbarButton.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

use newest lsp4j. no longer part of composite cause nobody knows how that is maintained

use newest lsp4j. no longer part of composite cause nobody knows how that is maintained

---

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1604] use 4.15 I-builds

[eclipse/xtext#1604] use 4.15 I-builds

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/ProgressReportingTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/refactoring/ProgressReportingTest.java

e.g. MarkOccurrencesTest and AbstractCompositeHoverTest.

[eclipse/xtext#1455] Close streams to fix various tests on windows.

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Also moved 'Oxygen' repository list before 'Photon'.
DO NOT MERGE UNTIL AVAILABILITY OF
- https://download.eclipse.org/tools/orbit/downloads/2020-03
- https://download.eclipse.org/eclipse/updates/4.15-I-builds

[eclipse/xtext#1606] Update Xtext.setup for Eclipse 2020-03

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java

[eclipse/xtext#1455] Close stream to fix Storage2UriMapperJdtImplTest.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/search/XtextEObjectSearchDialog.java

- Ensure that the matching elements label is made wide enough to fit the
entire horizontal space.

[#1317] Improve GUI Layout on the Open Model Element Dialog.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/ReconcilerReplaceRegion.java

see https://github.com/eclipse/xtext-core/pull/1355
Mind that the field `ReconcilerReplaceRegion#events` of type `List<DocumentEvent>` is not part of hashCode and equals methods (yet?). Reason is that I would like to hear your opinion on this first since `org.eclipse.jface.text.DocumentEvent` does not provide `hashCode()` or `equals()` methods.

Add hashCode() and equals() to ReconcilerReplaceRegion

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java

This PR aims at cleaning up the Domainmodel validator after the porting to Java (from Xtend):
- removed useless parenthesis, curly brackets, parameter types in lambdas
- turned most uses of IterableExtensions (nested calls) to Java streams (fluent style)
I left a use of IterableExtensions but we might change that as well.
Moreover, we can further remove local variable declarations that are then used for streams (but I'd like to have feedback about that first)

Some cosmetic changes to Domainmodel validator

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java

the first child should not be selected if there are no children.
Signed-off-by: Mathias Rieder <mathias.rieder@gmail.com>

[eclipse/xtext-eclipse#1336] fix check to prevent OutOfBoundsException

---

releng/org.eclipse.xtext.contributor/Xtext.setup

[eclipse/xtext-core#1244] update to LSP4J 0.9.0 release

[eclipse/xtext-core#1244] update to LSP4J 0.9.0 release

---

org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/SingleCodetemplateUiModule.java
org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/editor/embedded/CodetemplatesEmbeddedEditorActions.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorActions.java

[eclipse/xtext-eclipse#1361] fixed embedded editor context activation in templates editor in preference pages

[eclipse/xtext-eclipse#1361] fixed embedded editor context activation in templates editor in preference pages

---

releng/org.eclipse.xtext.contributor/Xtext.setup
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1685] use 4.16 ibuilds in latest target

[eclipse/xtext#1685] use 4.16 ibuilds in latest target

---

releng/org.eclipse.xtext.contributor/Xtext.setup

dropped obsolete egit/mylin/github site

dropped obsolete egit/mylin/github site

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/nature/ToggleXtextNatureCommand.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/StratumBreakpointAdapterFactory.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/XbaseBreakpointUtil.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/XbaseLineBreakpoint.java
org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/ClassFileBasedOpenerContributor.java
org.eclipse.xtext.ui.ecore/src/org/eclipse/xtext/ui/ecore/EcoreEditorOpener.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/compare/DefaultMergeViewer.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditorPropertyTester.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/toggleComments/ToggleSLCommentAction.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/utils/EditorUtils.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/FileOpener.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/preferences/PropertyAndPreferencePage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultRefactoringDocumentProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/NewFileWizardPrimaryPage.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/actions/ImportsAwareClipboardAction.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/actions/XbaseFoldingActionContributor.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JUnitLaunchShortcut.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JUnitPDELaunchShortcut.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaApplicationLaunchShortcut.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/LaunchShortcutUtil.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/launcher/SelectionUtil.java

change most of the direct calls to
org.eclipse.core.runtime.IAdaptable.getAdapter(Class<T>) to
org.eclipse.core.runtime.Adapters.adapt(Object, Class<T>) to also invite
registered AdapterFactories.
Signed-off-by: Mathias Rieder <mathias.rieder@gmail.com>

[eclipse/xtext-eclipse#1027] change getAdapter(..) to Adapters.adapt(..)

---

org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/ide/contentassist/antlr/PartialBuilderTestLanguageContentAssistParser.java
org.eclipse.xtext.ui.codetemplates.ide/src-gen/org/eclipse/xtext/ui/codetemplates/ide/contentassist/antlr/PartialCodetemplatesContentAssistParser.java
org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/ide/contentassist/antlr/PartialXmlContentAssistParser.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ide/src-gen/org/eclipse/xtext/example/arithmetics/ide/contentassist/antlr/PartialArithmeticsContentAssistParser.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/src-gen/org/eclipse/xtext/example/domainmodel/ide/contentassist/antlr/PartialDomainmodelContentAssistParser.java
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/src-gen/org/eclipse/xtext/example/fowlerdsl/ide/contentassist/antlr/PartialStatemachineContentAssistParser.java
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ide/src-gen/org/eclipse/xtext/example/homeautomation/ide/contentassist/antlr/PartialRuleEngineContentAssistParser.java
org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/PartialEcore2XtextTestContentAssistParser.java

[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/plugin.xml
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2

- Modify GenerateArithmetics.mwe2 workflow to completely supress the
creation of generator components, such as preference pages, builder
participant, open generated file command handler.

Simplify Xtext Simple Arithmetics Example.

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

- Modify the XtextGrammarQuickfixProvider to use system specific line
separators instead of the hard-coded '\n' symbol.
- Implement corresponding XtextGrammarQuickfixTest test case.

[#1391] Use System.lineSeparator in XtextGrammarQuickfixProvider.

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

[#1391] Use document.getLineDelimiter instead of System.lineSeparator.

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/labeling/XbaseLabelProvider.java

[eclipse/xtext-xtend#1034] restored old default (Object) case

[eclipse/xtext-xtend#1034] restored old default (Object) case

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/JvmAnnotationReferencePrinter.java

restored api (downstream compile errors in xtend)

restored api (downstream compile errors in xtend)

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java

- Reuse the recently introduced XtextUiInjectorProvider class instead
of maintaining an own one.

Refactoring the XtextGrammarQuickfixProviderTest test cases.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/XtextUIMessages.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/FoldingMessages.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/StatusWrapper.java

[eclipse/xtext#1738] use java.text.MessageFormat instead of com.ibm.icu.MessageFormat

[eclipse/xtext#1738] use java.text.MessageFormat instead of com.ibm.icu.MessageFormat

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/doubleClicking/AbstractWordAwareDoubleClickStrategy.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/CommonBreakIterator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/CommonWordIterator.java

[eclipse/xtext#1738] use java.text.BreakIterator instead of com.ibm.icu.BreakIterator

[eclipse/xtext#1738] use java.text.BreakIterator instead of com.ibm.icu.BreakIterator

---

org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/editor/autoedit/XtextAutoEditStrategyTest.java
org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/SemanticHighlightingTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/hyperlinking/HyperlinkHelperTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/outline/XtextOutlineTreeProviderTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java

- Reusing the recently introduced XtextUiInjectorProvider class.
- Reusing the inherited code from the org.eclipse.xtext.ui.testing
infrastructure.

Refactoring the org.eclipse.xtext.xtext.ui test cases.

---

org.eclipse.xtext.eclipse.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.ui.codetemplates/META-INF/MANIFEST.MF
org.eclipse.xtext.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/build.properties
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/build.properties
org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/build.properties
org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/build.properties

[eclipse/xtext#1738] removed no longer needed icu dependency

[eclipse/xtext#1738] removed no longer needed icu dependency

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ecoreInference/ProjectAwareXtendXtext2EcorePostProcessor.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextUiModule.java

marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated

marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/AbstractPluginProjectCreator.java

[eclipse/xtext#1738] removed icu from AbstractPluginProjectCreator

[eclipse/xtext#1738] removed icu from AbstractPluginProjectCreator

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/IssueDataTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/LinkingErrorTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java

- Eliminating duplicated code by inheriting the AbstractQuickfixTest
class from the AbstractEditorTest class instead of the
AbstractWorkbenchTest class.

org.eclipse.xtext.ui.tests.editor.quickfix refactoring.

---

org.eclipse.xtext.xtext.ui.tests/plugin.xml
org.eclipse.xtext.xtext.ui.tests/plugin.xml_gen

- Add changes to the plugin.xml_gen resulting from the regeneration of
the Xtext languages.
- Align formatting of the plugin.xml to the plugin.xml_gen to get a
readable, meaningful diff when comparing the two files.

Formatting org.eclipse.xtext.xtext.ui.tests plugin.xml files.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/IssueDataTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/LinkingErrorTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java

- Modify the IssueDataTest and the LinkingErrorTest test cases to use
the
org.eclipse.xtext.ui.testing.AbstractQuickfixTest API instead of the
org.eclipse.xtext.ui.tests.editor.quickfix.AbstractQuickfixTest internal
base class.
- Modify the CompositeQuickfixTest, MultiQuickFixTest and
SpellingQuickfixTest test cases to use the generated
QuickfixCrossrefTestLanguageUiInjectorProvider.
- Remove the obsolete getInjector() method from the AbstractQuickfixTest
base class.

Refactoring the org.eclipse.xtext.ui.tests.editor.quickfix test cases.

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractMultiQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java

[#1447] Rename AbstractQuickfixTest to AbstractMultiQuickfixTest.

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/RenameRefactoringIntegrationTest.java

- Eliminate duplicated code by using the
org.eclipse.xtext.ui.testing.util.IResourcesSetupUtil.fileToString API
method instead of an own implementation.

Refactoring the RenameRefactoringIntegrationTest test cases.

---

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1784] use 4.17 I-builds

[eclipse/xtext#1784] use 4.17 I-builds

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in latest + domainmodel

[eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in latest + domainmodel

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/fields/AbstractDetailsPart.java

This fixes an issue on the syntax coloring preference page:
when one color is changed, all other colors were shown as black
The preference store of field editors should not be replaced when
when a color is changed. The preference store is already a chained
preference store that contains the internal store.
This fixes bugzilla 564578

[bugzilla 564578] Fix wrong colors on colors preference page

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractMultiQuickfixTest.java

- Add a testMultiQuickfix() API method to the AbstractMultiQuickfixTest
class to provide an easy and compact way to test multi-quickfixes.

[#1447] Add AbstractMultiQuickfixTest.testMultiQuickfix API method.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractCodeMiningTest.java
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/codemining/CodeMiningTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/codemining/CodeMiningTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.java

AbstractCodeMiningTest abstract class to provide a base infrastructure
for testing the code mining capabilities.
- Extend the Xtext Examples by CodeMiningTest test cases to
demonstrate the usage of the AbstractCodeMiningTest class.

[#1497] Provide the AbstractCodeMiningTest abstract base class.

---

org.eclipse.xtext.builder.tests/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.builder/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.common.types.eclipse.tests/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.common.types.ui/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.eclipse.tests/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.ui.codetemplates.ui/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.ui.codetemplates/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/.settings/org.eclipse.xtend.shared.ui.prefs
org.eclipse.xtext.xtext.ui/.settings/org.eclipse.xtend.shared.ui.prefs

removed obsolete org.eclipse.xtend.shared.ui.prefs

removed obsolete org.eclipse.xtend.shared.ui.prefs

---

org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/RailroadSynchronizer.java

[eclipse/xtext-core#1561] Remove model listener when the railroad view is closed

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

- Enhanced the quick-fix to handle the case where a terminal-fragment is referenced as a hidden token in a Parser rule definition
- Added method createChangeToIssueResolution() to avoid duplicate 'Change to' quick-fix if there are multiple/different fixes for an issue
- Added quick-fix method fixUnresolvedEnumRule()
- Added unit-tests.
Signed-off-by: nbhusare <neerajbhusare@gmail.com>

Porting quickfixes for illegal rule references

---

releng/org.eclipse.xtext.contributor/Xtext.setup

[eclipse/xtext#1827] prepare oomph for Xtext 2.24 & Eclipse 2020-12

[eclipse/xtext#1827] prepare oomph for Xtext 2.24 & Eclipse 2020-12

---

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/AbstractWorkbenchTest.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractWorkbenchTest.java

Process UI events before & after setup & teardown
to avoid problems with wrong active shell in tests
Fixes #1538

Process UI events before & after setup & teardown

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

Replaced the hard-coded \t (tab) character with `o.e.x.formatting.IIndentationInformation`
Signed-off-by: nbhusare <neerajbhusare@gmail.com>

Replace the hard-coded \t (tab) character with o.e.x.formatting.IIndentationInformation

---

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java

Removed invalid terminal-fragment quick-fix proposal and the corresponding unit-test
Signed-off-by: nbhusare <neerajbhusare@gmail.com>

Avoid the quickfix to create a terminal fragment where the fragment usage would be illegal

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java

- Modify the DomainmodelCodeMiningProvider to display the number of
properties / operations as line header code minings before the entity
definition.
- Implement corresponding CodeMiningTest test cases.

[#1563] Add Domainmodel Codemining test cases

---

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/tests/ParallelBuildEnabledTest.java
org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/TargetPlatformUtil.java
org.eclipse.xtext.logging/src/org/eclipse/xtext/logging/EclipseLogAppender.java
org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/Activator.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/TargetPlatformUtil.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/util/BundleClasspathUriResolverTest.java

Refactor usages where a class can be referenced for the requested
bundle.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>

Bug 568152 - Use FrameworkUtil#getBundle instead of Platform#getBundle

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/ParallelBuilderParticipant.java

[#1577] switched order of while condition to make sure that we dont skip any things that are put to request queue
Fixes #1577

[#1577] switched order of while condition to make sure that we dont skip any things that are put to request queue

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Added requirement org.eclipse.license.feature.group
Added p2 repo http://download.eclipse.org/cbi/updates/license/
Other changes have been automatically applied by the Setup editor:
- Content of ResourceCreationTask
- Excluded working sets referred by name instead of index

[#1587] Add license feature

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/AnnotatedTextToString.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java

- Use fix number (5) of the - character as separator instead of
dynamically calculate it to match the same length as the longest line.

[#1505] Improve AbstractMultiQuickfixTest separator.

---

releng/org.eclipse.xtext.contributor/Xtext.setup
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#1885] update latest tp to 4.19-I-builds
DO NOT merge (yet) as 4.19-I-builds is not available yet

[eclipse/xtext#1885] update latest tp to 4.19-I-builds

---

releng/org.eclipse.xtext.contributor/Xtext.setup

[eclipse/xtext#1911] use specific m2e versions in Oomphed targets

[eclipse/xtext#1911] use specific m2e versions in Oomphed targets

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/SourceAttachmentPackageFragmentRootWalker.java

make SourceAttachmentPackageFragmentRootWalker accessible from Storage2UriMapperJavaImpl subclasses

make SourceAttachmentPackageFragmentRootWalker accessible from Storage2UriMapperJavaImpl subclasses

---

org.eclipse.xtext.ui/META-INF/MANIFEST.MF
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractFileTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractProjectTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/DefaultTemplateProjectCreator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/FileTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/FileTemplateProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/IFileGenerator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/IFileTemplateProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/IParameterPage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/IProjectGenerator.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/IProjectTemplateProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/NewFileWizardPrimaryPage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/NewProjectWizardTemplateSelectionPage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/ParameterComposite.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/ProjectTemplate.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/ProjectTemplateProcessor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateFileInfo.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateLabelProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateNewFileWizard.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateNewProjectWizard.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateParameterPage.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.xtend
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateProjectInfo.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateVariable.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/WorkspaceFileGenerator.java
org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java

expose org.eclipse.xtext.ui.wizard.template as API
Fixes eclipse/xtext#1962

expose org.eclipse.xtext.ui.wizard.template as API

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractContentProposalProvider.java

- Add content assist proposal labels styling for the text after the -
symbol, similar how JDT does it.
Signed-off-by: miklossy <miklossy@itmeis.de>

Styling the Content Assist Proposal Labels.

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/preferences/messages.properties

[eclipse/xtext-xtend#1198] adapt message for KeepLocalHistory with hint on new global flag

[eclipse/xtext-xtend#1198] adapt message for KeepLocalHistory with hint on new global flag

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/PluginImageHelper.java

When an image descriptor can be found through its name, it's not always registered for disposal. It should be.

Make sure all images are disposed

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java

Properly dispose TextLayout in  XbaseInformationControl
Fixes #1699

Properly dispose TextLayout in  XbaseInformationControl

---

Jenkinsfile

use 'unsuccessful' to catch all failure cases

use 'unsuccessful' to catch all failure cases

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/jvmmodel/DomainmodelJvmModelInferrer.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/jvmmodel/DomainmodelJvmModelInferrer.java

[eclipse/xtext-extras#695] fix jvm element removal in inferrer

[eclipse/xtext-extras#695] fix jvm element removal in inferrer

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildManagerAccess.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuilderStateDiscarder.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java

The window of opportunity for the autobuild is the time between
forgetting the last built state and the touch of the project in its own
job. Check if there is a known built state before touching the project
again.
Signed-off-by: Sebastian Zarnekow <sebastian.zarnekow@gmail.com>

[#1710] Don't touch the project again if it was already built

---

releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#2002] bootstrap against Xtext 2.26.0.M2

[eclipse/xtext#2002] bootstrap against Xtext 2.26.0.M2

---

Jenkinsfile

[eclipse/xtext#2003] run daily builds with Java 8 + 11 + 17

[eclipse/xtext#2003] run daily builds with Java 8 + 11 + 17

---

Jenkinsfile
org.eclipse.xtext.buildship/pom.xml
org.eclipse.xtext.ui.codemining/pom.xml
org.eclipse.xtext.ui.testing/pom.xml
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target
releng/org.eclipse.xtext.target/pom.xml
releng/org.eclipse.xtext.tycho.parent/pom.xml

[eclipse/xtext#2017] repare 2021-12 target && use 4.23 I-Builds

[eclipse/xtext#2017] repare 2021-12 target && use 4.23 I-Builds

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/JdtToBeBuiltComputer.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/IStorage2UriMapperJdtExtensions.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java

Since it is extremely unlikely that the JRE contains sources for which
an Xtext builder is supposed to be executed, the JdtTobeBuiltComputer
was always filtering the JRE from the build processing. The
Storage2UriMapperJavaImpl can do the same. Both share the same
implementation to make that decision.
Also replace pessimistic copies of maps by a synchronized collection in
the PackageFragmentRootData to avoid unnecessary copies of data.
In an unscientific coarse measurement, the time to init the cache for
500 projects was reduced from 15seconds to 40ms.

[Bug 574908] Improve performance of Storage2UriMapperJavaImpl in modular project

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml

[eclipse/xtext-core#1851] test disabling more repos to avoid maven-default-http-blocker warnings

[eclipse/xtext-core#1851] test disabling more repos to avoid maven-default-http-blocker warnings

---

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/IResourcesSetupUtil.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java

Currently, waitForBuild catches a CoreException and throws an
OperationCanceledException with just the message of the original
CoreException. Indeed, OperationCanceledException does not have a
constructor for passing also an exception. Without the original
exception, though, it is hard to understand what went wrong during the
test, since we lost the original exception's stacktracke

waitForBuild throws with reference to original exception

---

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#2038] build against 2022-06 in latest

[eclipse/xtext#2038] build against 2022-06 in latest

---

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/scoping/namespaces/WorkspaceProjectsStateTest.java

[Bug479450] adapt expectation to newly created org.eclipse.core.resources.prefs file in Eclipse 4.24

[Bug479450] adapt expectation to newly created org.eclipse.core.resources.prefs file in Eclipse 4.24

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.java

This updates compilation test expectations (https://github.com/eclipse/xtext-extras/pull/774 fixing https://github.com/eclipse/xtext-extras/issues/772).

772: updated dmodel compiler tests

---

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#2068] use 4.25 I-builds in latest

[eclipse/xtext#2068] use 4.25 I-builds in latest

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target

[eclipse/xtext#2068] use 2022-09 in latest & domainmodel

[eclipse/xtext#2068] use 2022-09 in latest & domainmodel

---

releng/org.eclipse.xtext.contributor/Xtext.setup

[eclipse/xtext#2068] use 4.25 I-builds in oomph

[eclipse/xtext#2068] use 4.25 I-builds in oomph

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

[eclipse/xtext#2086] use gef classic instead of legacy draw2d

[eclipse/xtext#2086] use gef classic instead of legacy draw2d

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

explicitely pull commons.io as platform no longer packages it
see eclipse-platform/eclipse.platform.releng.aggregator#444

explicitely pull commons.io as platform no longer packages it

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java

[eclipse/xtext#2087] dont add junit container anymore
[This basically undoes](https://github.com/eclipse/xtext-core/issues/666#issuecomment-389567981)
https://github.com/eclipse/xtext-core/issues/666#issuecomment-389567981
am not sure if we want to go that route or live with the container and the other deps for now
@szarnekow @kthoms what do you think

[eclipse/xtext#2087] dont add junit container anymore

---

org.eclipse.xtext.m2e/META-INF/MANIFEST.MF
org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/BinFolderConfigurator.java
org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/XtextProjectConfigurator.java
releng/org.eclipse.xtext.contributor/Xtext.setup

This PR aims to update `org.eclipse.xtext.m2e` Plugin to the M2E 2.0.1 release that is contributed to Eclipse 2022-09 M3 SimRel.
M2E 2.0 is a major release that has breaking changes in its API, that are incompatible with previous 1.x releases.
I updated the code and adjusted required bundle version ranges accordingly. Furthermore I update the target file to include the latest m2e release 2.0.1. That release is not yet in the 2022-09 release repo but will be with M3, so this change in advance should prevent trouble with the xText contribution.
I hope that is all correct, but please let me know if anything is wrong or missing.
Besides that I updated the setup and removed M2E-connectors incompatible with M2E 2.0.
The connectors for tycho-plugins are not required because M2E now has the …

Update to M2E 2.0

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/WizardNewXtextProjectCreationPage.java

dont propose Java 6-10 in Wizard anymore
@szarnekow what do you think? or should we keep 8+ and the error message as we have it in current Xtext 2.29?

dont propose Java 6-10 in Wizard anymore

---

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src-gen/org/eclipse/xtext/example/domainmodel/ui/AbstractDomainmodelUiModule.java

[eclipse/xtext-eclipse#1963] remove Class.forName guard for code minings

[eclipse/xtext-eclipse#1963] remove Class.forName guard for code minings
