eclipse/xtext-eclipse

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/ecore2xtext/NewXtextProjectFromEcoreWizard.java
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=494176
=> 494176: Warning: The file "plugin.xml" does not exist in the workspace

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/BasicDependencyCheckTest.java
=> moved BasicDependencyCheckTest to xtext-eclipse

org.eclipse.xtext.activities/plugin.properties, org.eclipse.xtext.ui.shared/plugin.properties, org.eclipse.xtext.ui.shared/plugin.xml
https://bugs.eclipse.org/bugs/show_bug.cgi?id=420434
https://bugs.eclipse.org/bugs/show_bug.cgi?id=420435
=> Fixed some Labeling issues in Xtext UI Contributions

org.eclipse.xtext.doc/contents/304_ide_concepts.html
Corrected minor documentation error
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483407
Signed-off-by: Bernhard Stadler <bernhard.stadler@itemis.de>
=> Corrected syntax error in documentation

releng/org.eclipse.xtext.contributor/Xtext.setup
=> #4 Removed org.springsource.ide.eclipse.gradle.core preferences since we use Buildship now

releng/org.eclipse.xtext.contributor/Xtext.setup
=> [#41] EGit UI: Set preference "Insert Signed-off-by Footer"

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
=> [494257] Capitalize 'maven' and 'gradle'

releng/org.eclipse.xtext.contributor/Xtext.setup
allow separate use of Mylyn and issue database
=> [#1070] New subproject "Xtext Issues"

org.eclipse.xtext.doc/contents/305_xbase.html
[366414] Made Documentation on use of Xbase more explicit
=> [366414] Made Documentation on use of Xbase more explicit

releng/org.eclipse.xtext.examples.feature/feature.properties, releng/org.eclipse.xtext.runtime.feature/feature.properties, releng/org.eclipse.xtext.ui.feature/feature.properties, releng/org.eclipse.xtext.xbase.feature/feature.properties
=> Double whitespace in feature description removed

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/XbaseValidationConfigurationBlock.java
[476779][validation] Make validation of non-static access to static member configurable
=> [476779][validation] Make validation of non-static access to static member configurable

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.java
=> [#74] Add SerializerTest

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextQuickAssistProcessor.java
[476752] added null check to XtextQuickAssistProcessor
=> [476752] added null check to XtextQuickAssistProcessor

org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/figures/layouts/RailroadConnectionRouter.java
[479328][Xtext] Fixed Memory Leak in Xtext Syntax Graph View
=> [479328][Xtext] Fixed Memory Leak in Xtext Syntax Graph View

org.eclipse.xtext.purexbase.eclipse.tests/.classpath, org.eclipse.xtext.testlanguages.ui/.classpath, org.eclipse.xtext.ui.codetemplates.tests/.classpath, org.eclipse.xtext.ui.codetemplates.ui/.classpath, org.eclipse.xtext.ui.tests/.classpath, org.eclipse.xtext.xbase.testlanguages.ui/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.tests/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui.tests/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ui/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ide/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ui/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/xbase.tutorial/.classpath, org.eclipse.xtext.xtext.ui.tests/.classpath, org.eclipse.xtext.xtext.ui/.classpath
=> [#81] Ignore optional compile problems on *-gen source folders

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/quickoutline/QuickOutlinePopup.java
[374716] [quickoutline] Status bar should show nicer key binding
=> [374716] [quickoutline] Status bar should show nicer key binding

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/WizardNewXtextProjectCreationPage.java
=> [481380] Disallow $ character in project name

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/Messages.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/WizardNewXtextProjectCreationPage.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/messages.properties
=> [421309] Validate file extension pattern

Jenkinsfile, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] deploy to build/maven-repository, don't use it as local repo

org.eclipse.xtext.junit4/META-INF/MANIFEST.MF
made dependency to pde optional. resolves #91
=> made dependency to pde optional. resolves #91

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/autoedit/MultiLineTerminalsEditStrategyTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/autoedit/MultiLineTerminalsEditStrategy.java
Signed-off-by: HBuender hendrik.buender@googlemail.com
=> [403812] Fix Search closing terminal in default_content region

releng/org.eclipse.xtext.contributor/Xtext.setup
=> Use Xtext,Xtend&MWE2 from "latest" compisite at Eclipse

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de
=> [#79] Configure lineDelimiter from workspace preference

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java
prevent potential npe in DefaultReferenceUpdater. fixes #127
=> prevent potential npe in DefaultReferenceUpdater. fixes #127

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/BuildCancellationTest.java, org.eclipse.xtext.builder.tests/src-no-jdt/org/eclipse/xtext/builder/noJdt/SingleProjectTest.java, org.eclipse.xtext.builder.tests/src-no-jdt/org/eclipse/xtext/builder/noJdt/TwoProjectsTest.java
made very flaky tests more stable. solves #31
=> made very flaky tests more stable. solves #31

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/JdtTypesProposalProvider.java
close #28
Signed-off-by: Stéphane Galland galland@arakhne.org
=> [commons][types] Retrieve the modifiers for a dirty state type.

releng/org.eclipse.xtext.contributor/Xtext.setup
=> Target platform: Upgrade org.junit to 4.12

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de
=> [449340] setDocumentContent: Handle RESOURCE_NOT_FOUND CoreException

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/GenerateDomainmodel.mwe2.launch, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/build.properties
- import package org.apache.commons.logging
- add com.ibm.icu as additional bundle
- remove XX:MaxPermSize arg from launch config
=> [#161] Added workflow runtime dependencies

releng/org.eclipse.xtext.contributor/Xtext.setup
Fixed Location Properties Generation for Oomph on Windows
=> Fixed Location Properties Generation for Oomph on Windows

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/encoding/WorkspaceEncodingProviderTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/WorkspaceEncodingProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperImpl.java
=> [510084] Consider project specific default encoding

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/RefactoringCrossReferenceSerializer.java
Second try with local editing.
=> Fix typo in refactoring error message

releng/org.eclipse.xtext.contributor/Xtext.setup
=> Upgrade API baseline for master and maintenance

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/UIBindings.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/compare/DefaultViewerCreator.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui/src-gen/org/eclipse/xtext/example/domainmodel/ui/AbstractDomainmodelUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ui/src-gen/org/eclipse/xtext/example/fowlerdsl/ui/AbstractStatemachineUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ui/src-gen/org/eclipse/xtext/example/homeautomation/ui/AbstractRuleEngineUiModule.java, org.eclipse.xtext.xtext.ui/src-gen/org/eclipse/xtext/xtext/ui/AbstractXtextUiModule.java
[415677] Language Specific Compare Viewer title
- Impl
- Regenerated Languages
=> [415677] Language Specific Compare Viewer title

org.eclipse.xtext.builder/plugin.xml, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/XtextBuildConsolePageParticipant.java
[459547] add close action to Xtext Builder Console
=> [459547] add close action to Xtext Builder Console

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectClasspathChangeAnalyzer.java
Issue #10: Fixed missing cases in JavaProjectClasspathChangeAnalyzer
=> Issue #10: Fixed missing cases in JavaProjectClasspathChangeAnalyzer

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/DefaultOutlineTreeProvider.java
=> Allow StructuralFeatureNodes with ImageDescriptors

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/IResourcesSetupUtil.java
[481981] use file encoding to create stringinputstream to create files
=> [481981] use file encoding to create stringinputstream to create files

org.eclipse.xtext.purexbase.ui/src/org/eclipse/xtext/purexbase/ui/autoedit/ReplAutoEdit.java
[371681] Enable PureXbase AutoEdit if there are warnings only
=> [371681] Enable PureXbase AutoEdit if there are warnings only

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/ImportingTypesProposalProvider.java
[415674] don't execute noop replacement on document for proposals that dont actually change anything when applied
=> [415674] better handling of noop proposals in Xbase/Xtend CA

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ParallelResourceLoader.java
[485182] Fixed Bug in ParallelResourceLoader regarding loading of non workspace resources (e.g. jar on classpath)
=> [485182] Fixed Bug in ParallelResourceLoader

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringPopup.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverProvider.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java
=> Don't make use of COLOR_INFO_* in Oxygen+ #197

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/tasks/preferences/TaskTagConfigurationBlock.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/tasks/preferences/TaskTagPreferencePage.java
=> [#191] Fixed broken Task Preference Page

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractContentProposalProvider.java
=> made getReplacementContextLength call customizable

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/DeclarativeQuickfixProviderTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/DeclarativeQuickfixProviderTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/AbstractDeclarativeQuickfixProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/Fix.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/Fixes.java
allow multiple quickfixes per method by making `@Fix` repeatable . #2
=>  allow multiple quickfixes. #2

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF
=> fixed test deps of examples

releng/org.eclipse.xtext.tycho.parent/pom.xml
Updated Tycho to Version 1.0.0
=> Updated Tycho to Version 1.0.0

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/JDTAwareEclipseResourceFileSystemAccess2.java
[495975] prevent npe for non source folder resources
=> [495975] prevent npe for non source folder resources

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
This change adds timestamp tracking for files outside workspace opened
in Xtext-based editors.
=> Fix for https://github.com/eclipse/xtext-eclipse/issues/209

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorFactory.java
Added support for line numbers in embedded editors. #212
=> Added support for line numbers in embedded editors. #212

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/templates/XtextTemplateContextTypeRegistry.java
[403446] Add Template Contexts for Keywords in Enum Rules
=> [403446] Add Template Contexts for Keywords in Enum Rules

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
=> fixed broken build

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/ContentAssistProcessorTestBuilder.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/ContentAssistProcessorTestBuilder.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.java
=> don't use deprecated Proposal.apply(Document) anymore. fixes #219

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/DerivedResourcesLookupMap.java
use reverse lookup map to find source files for generated files. #225
=> use reverse lookup map to find source files for generated files. #225

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/XtextBuildConsole.xtend, org.eclipse.xtext.builder/xtend-gen/org/eclipse/xtext/builder/debug/XtextBuildConsole.java
[483505] prevent NPE in ConsoleManager
=> [483505] prevent NPE in ConsoleManager

org.eclipse.xtext.ui.shared/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.tests/.project, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/.project, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui/.project, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/.project, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ui/.project, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl/.project
[456114][#229] Xtext nature overlay with the projectNatureImages extension point
=> [456114][#229] Xtext nature overlay with the projectNatureImages extension point

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/selection/AstSelectionProviderTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/selection/AstSelectionProvider.java
[515055] prevent NPEs in AstSelectionProvider
please review
=> [515055] prevent NPEs in AstSelectionProvider

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/JavaTypeQuickfixes.java
[486338]  [xtend][eclipse][quickfix] Add import quickfix should be case sensitive
=> [486338]  [xtend][eclipse][quickfix] Add import quickfix should be case sensitive

org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/preferences/AdvancedTemplatesPreferencePage.java
[381728] prevent NPE in AdvancedTemplatesPreferencePage
=> [381728] prevent NPE in AdvancedTemplatesPreferencePage

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringExecuter.java
[474781] do incremental build after rename
https://github.com/eclipse/xtext-xtend/issues/166
=> [474781]  do incremental build after rename

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ResourceLoaderProviders.java
[ParallelResourceLoader] Add Factory Method to ResourceLoaderProviders with an increased timeout
Solves #237
=> [ParallelResourceLoader] Add Factory Method to ResourceLoaderProviders with an increased timeout

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/preferences/OptionsConfigurationBlock.java
Avoids NPE in getPreferenceChanges
=> [515807] Initialize originalSettings

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/launcher/WorkflowLaunchUtils.java
=> [476754] null guard when no file is selected

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/launcher/WorkflowLaunchUtils.java
=> [515848] Avoid NPE for elements without id attribute

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/TraceForStorageProvider.java
null return value will be considered by
AbstractTraceForURIProvider#getTraceToTarget
=> [515846] getProjectConfig return null when service provider unavailable

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java
=> [515824] Catch and log exceptions on hover computation

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/HyperlinkHelper.java
=> [515804] Catch and log exceptions on hyperlink computation

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/occurrences/MarkOccurrenceActionContributor.java
create MarkOccurrenceAction as hidden by default. fixes #252
=> create MarkOccurrenceAction as hidden by default. fixes 252

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultRefactoringDocumentProvider.java
[516158]  Made  Workbench in DefaultRefactoringDocumentProvider actually optional
=> [516158]  Made  Workbench in DefaultRefactoringDocumentProvider actually optional

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/highlighting/XbaseHighlightingConfiguration.java
=> [409297] Added Constant for METHODS

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java
=> Do Better Test what we are actually doing and thus get more stable tests

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting/PreferenceStoreWhitespaceInformationProvider.java
Prevent NPE with old formatter
Fixes https://github.com/eclipse/xtext-core/issues/339
=> Prevent NPE with old formatter

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting/PreferenceStoreWhitespaceInformationProvider.java
better fix for  https://github.com/eclipse/xtext-core/issues/339
=> better fix for  https://github.com/eclipse/xtext-core/issues/339

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java
[474857] added additional null guard to DefaultReferenceUpdater
=> [474857] added additional null guard to DefaultReferenceUpdater

releng/org.eclipse.xtext.contributor/Xtext.setup
Remove base-line from oomph
Fixes https://github.com/eclipse/xtext-umbrella/issues/28
=> Remove base-line from oomph

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/xtext/ui/ContentAssistTest.java, org.eclipse.xtext.ui.tests/plugin.xml, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/AbstractBug326948Test.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/AbstractParametersContentAssistTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/Bug287941Test.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/Bug297909Test.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/ContentAssistCustomizingTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/CrossReferenceProposalTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/CurrentModelBugTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/ParametersContentAssistTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/ParametersContentAssistTestEx.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/TwoContextsContentAssistTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/contentassist/TwoParametersContentAssistTest.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/contentassist/XtextContentAssistTest.java
=> fixed more depreated tests

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlinePage.java
=> redraw outline only if not disposed

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java
Signed-off-by: HBuender <hendrik.buender@gmail.com>
=> [#289] Overwriting file.touch() behavior made easier

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/Messages.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/XbaseValidationConfigurationBlock.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/messages.properties, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/Messages.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/XtextValidatorConfigurationBlock.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/messages.properties
=> added support for info severity on pref pages #222

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.java
=> Delegated AbstractContentProposalProvider to IdeContentProposalProvider

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/guice/AbstractGuiceAwareExecutableExtensionFactory.java
see also eclipse/xtext-core#377
=> [462906] error handling when no Injector can be retrieved

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverDocumentationProvider.java
[#300] Fixed Calculation of DocRoot for Images in JavaDoc Hover
=> [#300] Fixed Calculation of DocRoot for Images in JavaDoc Hover

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/SyncUtil.java
=> fixed invalid thread access problem during refactoring #298

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/DefaultXbaseUiModule.java
[496665] bind XbaseResourceForEditorInputFactory for all xbase languages
=> [496665] bind XbaseResourceForEditorInputFactory for all xbase languages

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.xtend, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/outline/DisplaySafeSyncer.java, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/SyncUtil.java
=> fixed broken tests #307 #308

org.eclipse.xtext.ui.shared/plugin.xml, org.eclipse.xtext.xbase.ui/plugin.xml, org.eclipse.xtext.xtext.ui/plugin.xml
=> categorized some commands #304

releng/org.eclipse.xtext.contributor/Xtext.setup
- removed version constraint on m2e feature
- defined variables for m2e connector p2 repositories
- upgraded m2e tycho connector to 0.9.0-LATEST
=> Configuration of Maven tooling

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/refactoring/XbaseReferenceUpdater.java
Better Cancellation in DefaultReferenceUpdater.createReferenceUpdates / DefaultReferenceUpdater.processReferringResource #316
=> Better Cancellation in DefaultReferenceUpdater.createReferenceUpdates / DefaultReferenceUpdater.processReferringResource #316

org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/actions/ExportToFileAction.java
[473717] handle cancel event in ExportToFileAction (Xtext Syntax Graph View)
=> [473717] handle cancel event in ExportToFileAction (Xtext Syntax Graph View)

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/participant/ChangeConverter.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/participant/ReplaceFileContentChange.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/participant/TryWithResource.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring/participant/ChangeConverter.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring/participant/ReplaceFileContentChange.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring/participant/TryWithResource.java
Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>
=> [refactoring] allow to change contents from EMF resources

org.eclipse.xtext.m2e/META-INF/MANIFEST.MF
=> incr. version range for m2e

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/DomainmodelRuntimeModule.xtend, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/DomainmodelRuntimeModule.java
[490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages
=> [490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java
prevented npe in languagerootpreferencepage #342
=> prevented npe in languagerootpreferencepage #342

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
=> [476833] prevent npe in updateStatusLine

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EObjectDescriptionImplTest.java, org.eclipse.xtext.builder/emf-gen/org/eclipse/xtext/builder/builderState/impl/EObjectDescriptionImpl.java
- Added URI Cache to EObjectDescriptionImpl
- Added Some Tests
Fixes #337
=> Added URI Cache to EObjectDescriptionImpl

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AnnotationWithQuickFixesHover.java
=> [514608] Assure that CompletionProposalRunnable#proposals can't be null

org.eclipse.xtext.xbase.ui/.classpath, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/actions/ImportsAwareClipboardAction.java
=> [521918] Handle SWTError

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractCompletionProposalFactory.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractContentProposalProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.java
=> Improved UiToIdeContentProposalProvider

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java
introduced XbaseProposalCreator instead of anonymous inner subclass of DefaultProposalCreator to allow better extensibility #365
=> introduced XbaseProposalCreator

releng/org.eclipse.xtext.contributor/Xtext.setup
=> removed b3 from tooling #37 #370

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/RefactoringCrossReferenceSerializer.java
=> Fixed Missleading warning when refactoring #317

org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java
=> fix XtextGrammarRefactoringIntegrationTest #17

org.eclipse.xtext.purexbase.eclipse.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase.ui/plugin.xml_gen, org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/PureXbaseExecutableExtensionFactory.java, org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/internal/PurexbaseActivator.java, org.eclipse.xtext.xbase.ui/plugin.xml_gen, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/XbaseWithAnnotationsExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/XbaseExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/XtypeExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/internal/XbaseActivator.java
see also eclipse/xtext-extras#182
=> Regenerated Xbase & PureXbase

org.eclipse.xtext.testlanguages.ui/plugin.xml, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/backtracking/ui/BeeLangTestLanguageExecutableExtensionFactory.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/backtracking/ui/ExBeeLangTestLanguageExecutableExtensionFactory.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/backtracking/ui/SimpleBeeLangTestLanguageExecutableExtensionFactory.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/noJdt/ui/AbstractNoJdtTestLanguageUiModule.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/noJdt/ui/NoJdtTestLanguageExecutableExtensionFactory.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/ui/AbstractXtextGrammarTestLanguageUiModule.java, org.eclipse.xtext.testlanguages.ui/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/ui/XtextGrammarTestLanguageExecutableExtensionFactory.java
=> Regenerated test languages

org.eclipse.xtext.purexbase.ui/plugin.xml, org.eclipse.xtext.purexbase.ui/plugin.xml_gen, org.eclipse.xtext.testlanguages.ui/plugin.xml, org.eclipse.xtext.testlanguages.ui/plugin.xml_gen
=> [#379] Contribute org.eclipse.core.contenttype.contentTypes

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/QuickAssistInvocationContext.java
=> [525395] Add guard - viewer's control might be disposed

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.java
=> fixed broken tests

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/ReferenceUpdaterDispatcher.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/DefaultLinkedPositionGroupCalculator.java
Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>
=> GH-284 use fragment path URIs for rename refactoring

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtTypeProvider.java, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler.java
fixed compatibility issues with eclipse oxygen 1a / photon #393
=>  fixed compatibility issues with eclipse oxygen 1a / photon #393

org.eclipse.xtext.testlanguages.ui/plugin.xml
=> removed duplicate extensions

releng/org.eclipse.xtext.contributor/Xtext.setup
=> Add target platforms with staging repos for Oxygen/Photon

org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/ui/quickfix/QuickfixCrossrefTestLanguageQuickfixProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/IMultiModification.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/IMultiModificationContext.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/IMultiModificationWithContext.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/MultiModification.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/MultiModificationContext.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/IssueResolutionAcceptor.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/WorkbenchMarkerResolutionAdapter.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/quickfix/WorkbenchMarkerResolutionAdapter.java
=> [MultiQuickFix] minor API cleanup

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java, org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/refactoring/AbstractResourceRelocationTest.java
=> Don't use autobuild in tests to avoid flakyness

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/AbstractIssueResolutionProviderAdapter.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
=> [QuickFix] support multi- and non-multi resolution on same marker

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceQuery.java
[526246] handle cancellation in ReferenceQuery
=> [526246] handle cancellation in ReferenceQuery

releng/org.eclipse.xtext.oxygen.target/.project, releng/org.eclipse.xtext.oxygen.target/org.eclipse.xtext.oxygen.target.target, releng/org.eclipse.xtext.oxygen.target/pom.xml, releng/org.eclipse.xtext.photon.target/.project, releng/org.eclipse.xtext.photon.target/org.eclipse.xtext.photon.target.target, releng/org.eclipse.xtext.photon.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml, releng/pom.xml
added support for build with Photon and Oxygen
=> added support for build with Photon and Oxygen

org.eclipse.xtext.builder.tests/src-no-jdt/org/eclipse/xtext/builder/noJdt/AbstractBuilderTest.java, org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractBuilderTest.java, org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/MockJavaProjectProvider.java, org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/TargetPlatformUtil.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/TargetPlatformUtil.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/AbstractXbaseContentAssistBugTest.xtend, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistTest.java, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/editor/AbstractXbaseContentAssistBugTest.java, org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/contentassist/XtextContentAssistTest.java
fixed target platform util to work better on oxygen+ #439
=> fixed target platform util to work better on oxygen+ #439

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextReconciler.java
Cancel reconciler when uninstalling #446
=> Cancel reconciler when uninstalling #446

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/validation/MarkerEraser.java
#449
Signed-off-by: Hendrik Eeckhaut <hendrik.eeckhaut@sigasi.com>
=> Made deleteMarkers non-final

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/.classpath, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/build.properties, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/src-gen/org/eclipse/xtext/example/arithmetics/ide/AbstractArithmeticsIdeModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/xtend-gen/org/eclipse/xtext/example/arithmetics/ide/ArithmeticsIdeModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ide/xtend-gen/org/eclipse/xtext/example/arithmetics/ide/ArithmeticsIdeSetup.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/services/ArithmeticsGrammarAccess.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ide/src-gen/org/eclipse/xtext/example/domainmodel/ide/AbstractDomainmodelIdeModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/services/DomainmodelGrammarAccess.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ide/src-gen/org/eclipse/xtext/example/fowlerdsl/ide/AbstractStatemachineIdeModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ui/src-gen/org/eclipse/xtext/example/fowlerdsl/ui/AbstractStatemachineUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ide/src-gen/org/eclipse/xtext/example/homeautomation/ide/AbstractRuleEngineIdeModule.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation/src-gen/org/eclipse/xtext/example/homeautomation/services/RuleEngineGrammarAccess.java
=> regeneated examples #418

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/internal/ArithmeticsActivator.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel.ui/src-gen/org/eclipse/xtext/example/domainmodel/ui/internal/DomainmodelActivator.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.fowlerdsl.ui/src-gen/org/eclipse/xtext/example/fowlerdsl/ui/internal/FowlerdslActivator.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.homeautomation.ui/src-gen/org/eclipse/xtext/example/homeautomation/ui/internal/HomeautomationActivator.java
=> regenated example languages after j9 code generator changes

org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/tests/ArithmeticsParsingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/tests/interpreter/CalculatorTest.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/labeling/ArithmeticsLabelProvider.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/outline/ArithmeticsOutlineTreeProvider.java, org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.arithmetics/xtend-gen/org/eclipse/xtext/example/arithmetics/scoping/ArithmeticsScopeProvider.java
=> regenerated xtend code (java 9 java.lang.Module conflict)

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/DontAskAgainDialogs.java
=> Fixed typos

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
1. Add a project to eclipse
2. Open a file in this project
3. Close eclipse
4. Remove the project
5. Open eclipse
=> Prevent NPE

Jenkinsfile, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-luna.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
Fixed problem with Target Platforms not being properly installed #472
=> Fixed problem with Target Platforms not being properly installed #472

org.eclipse.xtext.builder/.project, org.eclipse.xtext.common.types.edit/.project, org.eclipse.xtext.common.types.shared.jdt38/.project, org.eclipse.xtext.common.types.shared/.project, org.eclipse.xtext.common.types.ui/.project, org.eclipse.xtext.junit4/.project, org.eclipse.xtext.m2e/.project, org.eclipse.xtext.ui.ecore/.project, org.eclipse.xtext.ui.shared/.project, org.eclipse.xtext.ui.testing/.project, org.eclipse.xtext.ui/.project, org.eclipse.xtext.xbase.junit/.project, org.eclipse.xtext.xbase.ui.testing/.project, org.eclipse.xtext.xbase.ui/.project, org.eclipse.xtext.xtext.ui.graph/.project, org.eclipse.xtext.xtext.ui/.project
=> [eclipse/xtext#1156] Removed PDE API Tool configuration

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
=> use oxygen sr2

org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/AbstractPureXbaseUiModule.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/AbstractXbaseWithAnnotationsUiModule.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/AbstractXbaseUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src-gen/org/eclipse/xtext/example/domainmodel/ui/AbstractDomainmodelUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/src-gen/org/eclipse/xtext/example/homeautomation/ui/AbstractRuleEngineUiModule.java
Regenerated languages affected by the faulty generation from issue [#463]
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> [#463] Fixed faulty editor binding

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Quick fix reuses logic for detection of the warning and hence is able to
handle all cases.
Add test cases for many cases.
Change-Id: I82667455d23cbeceddef7725fa83f1892c6d9d32
=> [#51] Add quick fix for create warning.

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Also for static model case.
Add test case for rule with "returns" expression.
Change-Id: I3bdc260e9e95e117277b55ee781014faf5aec579
=> [#51] Handle case where rule contains a "returns"

org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/EclipseWorkspaceConfig.java, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.java
=> [420984] Compiler optimization: Suppress unused exception variable

releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.releng/distrobuilder/aggregator/common.b3aggrcon, releng/org.eclipse.xtext.releng/releng/mirroring/Latest.b3aggr, releng/org.eclipse.xtext.releng/releng/mirroring/xpand-mwe-orbit.b3aggrcon, releng/org.eclipse.xtext.releng/releng/tests/tests-eclipseserver.target, releng/org.eclipse.xtext.releng/target-platforms/developer-luna.target, releng/org.eclipse.xtext.releng/target-platforms/developer-mars.target
More details see at
https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg15176.html
=> [#1165] EMF repository URLs have changed

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/LinkedHashSetQueueTest.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/LinkedHashSetQueue.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/QueuedBuildData.java
[#40] use set based queue instead of linked list
=> [#40] use set based queue instead of linked list

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java
[#535] Add Cache for BuilderParticipant.getOutputConfigurations(IBuildContext context)
=> [#535] Add Cache for BuilderParticipant.getOutputConfigurations(IBuildContext context)

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
=> [#530] build against latest photon

org.eclipse.xtext.common.types.shared/src/org/eclipse/xtext/common/types/shared/SharedCommonTypesModule.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/DefaultUiModule.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XbaseUiModule.xtend, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/copyqualifiedname/XbaseCopyQualifiedNameService.xtend, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/XbaseUiModule.java, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/editor/copyqualifiedname/XbaseCopyQualifiedNameService.java
Change-Id: I7f8252f89ef082fe38223e44d82c5294b8cb9e08
=> [#517] Bind deprecated interfaces in addition to new ones.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/PluginImageHelper.java
Signed-off-by: Stéphane Galland <galland@arakhne.org>
=> Enable PluginImageHelper getting image from another plugin.

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/tasks/TaskMarkerContributorTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/tasks/TaskMarkerContributorTest.java
[#562] Fixed TaskMarkerContributorTest order dependency
=> [#562] Fixed TaskMarkerContributorTest order dependency

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/model/generated/Arithmetics.genmodel, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/Import.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/AbstractDefinitionImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/ArithmeticsFactoryImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/ArithmeticsPackageImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/DefinitionImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/ImportImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/ModuleImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/impl/NumberLiteralImpl.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/util/ArithmeticsAdapterFactory.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/arithmetics/util/ArithmeticsSwitch.java
[#557] regenerated example against emf 2.14
=> [#557] regenerated example against emf 2.14

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
update to tycho 1.1.0 https://github.com/eclipse/xtext/issues/1172
=> update to tycho 1.1.0

Jenkinsfile
=> added hint on target platform to label

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
[#522] Fixed XtextGrammarQuickfixProviderTest
=> [#522] Fixed XtextGrammarQuickfixProviderTest

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java, org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/JdtTypesProposalProvider.java
https://github.com/eclipse/xtext-core/issues/506
=> get rid of reflective code.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
[407999] make MarkerResolutionGenerator work with multipage editors as well
=> [407999] make MarkerResolutionGenerator work with multipage editors as well

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java
Create new project name für each test case such that builds in tests can
not influence other cases.
Change-Id: I594efb9f1bf4964ca5b77640d0df8cb3bd3b7b55
=> #522 Remove resource listener after test hase been finisched.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/preferences/OptionsConfigurationBlock.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringExecuter.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/MultiOrganizeImportsHandler.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/navigation/JvmImplementationOpener.java
=> [#579] Replace usage of deprecated SubProgressMonitor by SubMonitor

org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java
[#522] wait for build before refactoring
=> [#522] wait for build before refactoring

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java
Change-Id: I84a696eda8f8dfe89b39edef70fe1e4ce3622566
=> #522 Sync to build job to ensure that even a 300ms build delay is ok.

org.eclipse.xtext.builder.tests/src-no-jdt/org/eclipse/xtext/builder/noJdt/TwoProjectsTest.java
=> [#581] Fixed Flaky Test

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java
[#551] Notify on Real Changes only
=> [#551] Notify on Real Changes only

org.eclipse.xtext.junit4/xtend-gen/org/eclipse/xtext/junit4/logging/LoggingTester.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/EclipseProjectConfig.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/EclipseSourceFolder.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/EclipseWorkspaceConfig.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/JdtProjectConfig.java, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/JavaSource.java, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/RegisteringFileSystemAccess.java
Regenerated against lastest xbase-lib
https://github.com/eclipse/xtext/issues/1174
=> Regenerated against lastest xbase-lib

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ReplaceFileContentChange.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/ReplaceFileContentChange.java
... in the LTK Rename Refactoring Dialog
=> [refactoring] display namens of non-xtext resource

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/AbstractTextEditComposerTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
=> Fixes #589: ChangeSerializerComposerTest + CompositeQuickfixTest

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/tasks/TaskMarkerContributorTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/tasks/TaskMarkerContributorTest.java
Signed-off-by: René Purrio <rpurrio@itemis.de>
=> resolve small issue in class TaskMarkerContributorTest

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/.project, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/.settings/org.eclipse.core.resources.prefs, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/build.properties, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/feature.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/repository/.project, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/repository/.settings/org.eclipse.core.resources.prefs, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/repository/category.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/repository/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/.project, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/.settings/org.eclipse.core.resources.prefs
Signed-off-by: René Purrio <rpurrio@itemis.de>
=> Extend the domainmodel example build by a repository and a feature.

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/GlobalRegistries.java
=> [522715] Copy/Clear new EAnnotationValidator registry map in EMF 2.14+.

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/ContentAssistProcessorTestBuilder.java, org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/util/PluginProjectFactoryTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/util/PluginProjectFactoryTest.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/hierarchy/XtextCallHierarchyBuilderTest.xtend, org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/hierarchy/XtextCallHierarchyBuilderTest.java
I could not yet check if the tests still work on Unix-based systems, but I am optimistic that nothing is broken by these changes.
Signed-off-by: Florian Stolte <fstolte@gmx.de>
=> Fixed some tests that were failing on windows due to line ending issues.

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/Messages.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/XtextValidatorConfigurationBlock.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/validation/messages.properties
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
=> #664 [Grammar] Add Support for more Annotations

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/JavaBuilderState.xtend, org.eclipse.xtext.idea.generator/src/org/eclipse/xtext/idea/generator/IdeaPluginGenerator.xtend, org.eclipse.xtext.idea.generator/src/org/eclipse/xtext/idea/generator/parser/antlr/XtextAntlrIDEAGeneratorFragment.xtend, org.eclipse.xtext.purexbase.ui/src/org/eclipse/xtext/purexbase/ui/PureXbaseUiModule.xtend, org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/util/PluginProjectFactoryTest.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/UiToIdeContentProposalProvider.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/WorkbenchMarkerResolutionAdapter.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationStrategyRegistry.xtend, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/ProjectVariable.xtend, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.xtend, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/junit/typesystem/PublicTypesForTesting.xtend, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/hyperlinking/AbstractHyperlinkingTest.xtend, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseEditorInputRedirector.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/jvmmodel/RuleEngineJvmModelInferrer.xtend
=> Removed redundant modifiers

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/resource/AbstractScopeResourceDescriptionsTest.java
=> Added throw keyword to Throwables.propagate

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/JavaVersionExtendedTest.java
=> [eclipse/xtext#1177] Adapt test to test Java 10 as well.

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/WizardNewXtextProjectCreationPage.java
sort bree as they occurr in JavaVersion
=> sort bree as they occurr in JavaVersion

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/Activator.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/Messages.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/messages.properties, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-luna.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
- Extend target platforms by JUnit 5 dependencies
- Extended New Project Wizard: JUnit version is selectable
=> JUnit 5 support

releng/org.eclipse.xtext.contributor/Xtext.setup
=> use asm 6.1.1 in oomph

org.eclipse.xtext.ui/schema/fileTemplate.exsd
=> [#651] Add missing .exsd file to describe extension point.

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
Until we can reliably detect availability of JUnit5
=> [#666] Make JUnit4 default

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/preferences/ResetPromptDialogSettingsField.java
[#656] Fixed Margin Problem in Reset Preference Page
Old:
New:
=> [#656] Fixed Margin Problem in Reset Preference Page

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-oxygen.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-oxygen.tpd, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-luna.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
=> [eclipse/xtext#1198] Update Orbit URL to Photon M7

releng/org.eclipse.xtext.contributor/Xtext.setup
=> [eclipse/xtext-core#666] Add JUnit 5 to modular target

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AbstractProblemHoverTest.java
=> Removed hover test due to inconsistency across platforms

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java
This will add the JUnit library containerto test projects with the selected JUnit version
=> [eclipse/xtext-core#666] Configure JUnit library container in test proj.

org.eclipse.xtext.doc/contents/102_domainmodelwalkthrough.html, org.eclipse.xtext.doc/contents/103_domainmodelnextsteps.html, org.eclipse.xtext.doc/contents/104_jvmdomainmodel.html, org.eclipse.xtext.doc/contents/301_grammarlanguage.html, org.eclipse.xtext.doc/contents/302_configuration.html, org.eclipse.xtext.doc/contents/303_runtime_concepts.html, org.eclipse.xtext.doc/contents/304_ide_concepts.html, org.eclipse.xtext.doc/contents/305_xbase.html, org.eclipse.xtext.doc/contents/306_mwe2.html, org.eclipse.xtext.doc/contents/307_special_languages.html, org.eclipse.xtext.doc/contents/308_emf_integration.html, org.eclipse.xtext.doc/contents/310_eclipse_support.html, org.eclipse.xtext.doc/contents/310_web_integration.html, org.eclipse.xtext.doc/contents/320_idea_support.html, org.eclipse.xtext.doc/contents/330_web_support.html, org.eclipse.xtext.doc/contents/350_continuous_integration.html, org.eclipse.xtext.doc/contents/index.html, org.eclipse.xtext.doc/contents/toc.xml
=> [#485] regenerated help

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/FSSynchronizationTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.java
=> [#681] ignored failing tests

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/model/DocumentLockerTest.java
There is no guarantee from the VM that a write to an array from one
thread is visible to any other thread at any time. This will happen
especially when there is a high load with high memory pressure. In this
case I guess the started thread passes the "check.set" but this value
does not be shown to the main thread. That waits sometimes for 40sec in
the while loop until the first threads timed out.
Replaced the code with a CountDownLatch that does not suffer from this
issue. Flakyness should be gone.
=> [#681] Fix race condition.

org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/FSSynchronizationTest.java, org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.xtend, org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.java
=> [#681] Fixed FSSynchronizationTest by disablement of autobuild.

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/ValidationTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/ValidationTest.java
=> [NONE] Add ValidationTest test cases to the 'Home Automation' example.

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ParallelResourceLoader.java
[#665] Fixed Issue with Parallel Loaders and Out-Of-Sync jar files in workspace
=> [#665] Fixed Issue with Parallel Loaders and Out-Of-Sync jar files in workspace

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/TraceForTypeRootProvider.java
problem when opening a file from File search.
Signed-off-by: Arshad <a.adavani@itemis.com>
=> Fixed Java Model Exception: Java Model Status [ "folder "does not exist]

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [eclipse/xtext#1225] Update to Tycho 1.2.0

org.eclipse.xtext.xtext.ui.examples/build.xml, org.eclipse.xtext.xtext.ui.examples/plugin.xml
=> [#713] Ensure that the fowlerdsl.tests plugin is zipped and packaged.

org.eclipse.xtext.xtext.ui.examples/plugin.xml
=> Usage of consistent descriptions of the Xtext Example plug-ins.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-luna.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
=> updated orbit to photon release

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectFactory.java
=> [#677] Fix NPE when no output folder is defined.

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
=> use photon release update site

releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1231] added workaround
=> [eclipse/xtext#1231] added workaround

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.java
[536925] prevent npe in logging
=> [536925] prevent npe in logging

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.java
=> [#736] Implement additional Homeautomation Example highlighting tests.

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.java
=> Add RuleEngineContentAssistTest to the 'Xtext Homeautomation' example.

org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/xtend-gen/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.java
=> regenerated against latest xtend

org.eclipse.xtext.common.types.shared.jdt38/META-INF/MANIFEST.MF
=> set java exec env to java 8

org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml
[eclipse/xtext#1228] build codemining and testing against hardcoded photon only on oxygen
=> [eclipse/xtext#1228] build codemining and testing against hardcoded photon only on oxygen

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.java
- The more tests are detecting the bug, the better the fix will be.
=> [#755] Implement additional DomainModel Example Template Proposal test.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/TargetURIConverter.java
Needs https://github.com/eclipse/xtext-core/pull/810 to be merged first
=> Made UI TargetURIConverter extends from non ui one

Jenkinsfile
=> [#747] archive junit logs

org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[#780] proper fix for profiles in submodules
=> [#780] proper fix for profiles in submodules

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateNewProjectWizard.java
=> [#789] Show the simple project name on the Project Wizard Advanced Page.

org.eclipse.xtext.builder.tests/plugin.xml_gen, org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/ide/AbstractBuilderTestLanguageIdeModule.java, org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/ide/contentassist/antlr/BuilderTestLanguageParser.java, org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/internal/TestsActivator.java, org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/ui/AbstractBuilderTestLanguageUiModule.java, org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/validation/AbstractBuilderTestLanguageValidator.java, org.eclipse.xtext.ui.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.ui.tests/plugin.xml_gen, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/bracketmatching/validation/AbstractBmTestLanguageValidator.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/noTerminalExtension/NoTerminalExtensionPackage.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/noTerminalExtension/impl/NoTerminalExtensionPackageImpl.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/quickfix/validation/AbstractQuickfixCrossrefTestLanguageValidator.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/refactoring/validation/AbstractRefactoringTestLanguageValidator.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/refactoring/validation/AbstractReferringTestLanguageValidator.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/validation/AbstractFoldingTestLanguageValidator.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/validation/AbstractTestLanguageValidator.java
[eclipse/xtext#1227] regenerated testlanguages
=> [eclipse/xtext#1227] regenerated testlanguages

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> better workaround for signing issue

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/EclipseBasedShouldGenerate.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/generator/EclipseBasedShouldGenerate.java
Not strictly related to the preformance of the JavaSourceLang but still interesting to avoid unnecessary object allocation.
=> [xtext/xtext-gradle-plugin#120] performance optimization java source lang

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd
[eclipse/xtext-core#822] Build Against 2018-09
=> [eclipse/xtext-core#822] Build Against 2018-09

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1278] removed xtext-idea from oomph
=> [eclipse/xtext#1278] removed xtext-idea from oomph

Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1273] build against 2018-09 and 2018-12
=> [eclipse/xtext#1273] build against 2018-09 and 2018-12

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/generator/StatemachineGenerator.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/generator/StatemachineGenerator.java
=> Reduce visibility of StatemachineGenerator helper methods to protected.

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
[eclipse/xtext#1298] updated to 2018-09/4.9 final
=> [eclipse/xtext#1298] updated to 2018-09/4.9 final

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/src/org/eclipse/xtext/example/arithmetics/tests/ArithmeticsParsingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/src/org/eclipse/xtext/example/arithmetics/tests/interpreter/CalculatorTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/ArithmeticsUiModule.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/contentassist/ArithmeticsProposalProvider.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/ArithmeticsRuntimeModule.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/scoping/ArithmeticsScopeProvider.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/validation/ArithmeticsValidator.xtend
- Formatting the source code.
- Organizing the import statements.
=> Cleaning up the Xtext Simple Arithmetics Example.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/quickfix/DomainmodelQuickfixProvider.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/quickfix/DomainmodelQuickfixProvider.java
=> DomainModel Example: remove unnecessary whitespace from quickfix descr.

releng/org.eclipse.xtext.contributor/Xtext.setup
[#828] Updated Setup to 4.9 final. introduced 4.10-ibuilds
=> [#828] Updated Setup to 4.9 final. introduced 4.10-ibuilds

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/TypeChooser.java
[539215] Fixed ArrayIndexOutOfBoundsException when no type selected
=> [539215] Fixed ArrayIndexOutOfBoundsException when no type selected

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend
=> Format the source code of the AbstractQuickfixTest.xtend file.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java
=> [539532] Add disposal check

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
=> updated to orbit 2018-12-M1

org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.java, org.eclipse.xtext.common.types.ui/xtend-gen/org/eclipse/xtext/common/types/ui/notification/JavaBuilderState.java, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/DeclarativeQuickfixProviderTest.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/TryWithResource.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationStrategyRegistry.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/rename/DefaultLinkedPositionGroupCalculator2.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/tasks/TaskMarkerContributor.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/hover/JvmAnnotationReferencePrinter.java, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/editor/hierarchy/OpenCallHierarchyHandler.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/xtend-gen/org/eclipse/xtext/example/arithmetics/validation/ArithmeticsValidator.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/editor/hierarchy/OpenAssociationHierarchyHandler.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/validation/StatemachineValidator.java, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/hierarchy/OpenCallHierarchyHandler.java
=> regenerated with newer xtend

releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
[#841] address removal of equinox.ds in platform 4.10
=> [#841] address removal of equinox.ds in platform 4.10

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
[#870] Fixed Wizard Problem when no PDE available
=> [#870] Fixed Wizard Problem when no PDE available

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/navigation/XbaseHyperLinkHelper.java
- Extend the XbaseHyperLinkHelper to provide hyperlinks on types
referenced in javadoc comments.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=431101
=> https://github.com/eclipse/xtext-xtend/issues/372 Hyperlinks in javadoc.

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/XbaseQuickfixProvider.java
[eclipse/xtext-xtend#620] add multi quickfix for != -> !== and == -> ===
=> [eclipse/xtext-xtend#620] add multi quickfix for != -> !== and == -> ===

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/Activator.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
[eclipse/xtext-eclipse#657] removed isJUnit5Available. made junit 5 default
=> [eclipse/xtext-eclipse#657] removed isJUnit5Available. made junit 5 default

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/quickfix/QuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/quickfix/QuickfixTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/src/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/src/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineParsingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineParsingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineQuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineContentAssistTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineHighlightingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineQuickfixTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineQuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineHighlightingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineQuickfixTest.java
=> Add author tag to the Xtext example test classes contributed by me.

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
=> [540613] Added scheduling option ALL_XTEXT_PROJECTS_AND_JDTEXTFOLDER

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/pom.xml
=> [#911] use latest lsp4j

org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/XtextProjectConfigurator.java
[#788] fixed deprecations in xtext m2e inregration
=> [#788] fixed deprecations in xtext m2e integration

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
=> named storage 2 uri mapper java initializer thread

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
=> switched to orbit 2019-03

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ToBeBuiltComputer.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/IStorage2UriMapper.java
storage2Project.getSecond() might return null
=> [#924] doRemoveProject: add null guard

releng/org.eclipse.xtext.tycho.parent/pom.xml
Signed-off-by: Prajwal Gowda <pgowda@itemis.de>
@cdietrich  could you please review it
=> bootstraping version to 2.16.0

Jenkinsfile, releng/org.eclipse.xtext.tycho.parent/pom.xml, releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
[eclipse/xtext#1322] switch  to tycho 1.3
=> [eclipse/xtext#1322] switch  to tycho 1.3

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/MultiImportOrganizer.java
Fix exception in case a file has already organized imports.
=> eclipse/xtext-xtend#655 Fix exception.

Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1363] prepare build against 2019-03
=> [eclipse/xtext#1363] prepare build against 2019-03

releng/org.eclipse.xtext.contributor/Xtext.setup
=> switched to final 4.10 repo

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
=> fixed domainmodel tests on mac

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1365] added support for 2019-03 to oomph
=> [eclipse/xtext#1365] added support for 2019-03 to oomph

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
[eclipse/xtext#1283] update to MWE 2.10 M2
=> [eclipse/xtext#1283] update to MWE 2.10 M2

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java
[#965] Fixed BasicIndexOutOfBoundsException in Domainmodel Codemining
=> [#965] Fixed BasicIndexOutOfBoundsException in Domainmodel Codemining

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/TypeChooser.java
=> made non vararg invocation clear

org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/XtextProjectConfigurator.java
=> fixed guava deprecations

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1283] update to MWE 2.10
do not merge before mwe 2.10 is out
=> [eclipse/xtext#1283] update to MWE 2.10

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/XtextResourceSetProvider.java
See https://github.com/itemis/xtext-reference-projects/issues/41
=> Avoid NPE during cleanup build job

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend, org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Signed-off-by: Lorenzo Addazi <addazi.lorenzo@gmail.com>
=> Bug 410479 - [grammar] Add quickfix splitting keywords with spaces.

releng/org.eclipse.xtext.contributor/Xtext.setup
fixed broken oomph setup (junit 5 in 2019-03)
=> fixed broken oomph setup (junit 5 in 2019-03)

org.eclipse.xtext.doc/contents/103_domainmodelnextsteps.html, org.eclipse.xtext.doc/contents/350_continuous_integration.html
=> regenerated docs

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend, org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Signed-off-by: Lorenzo Addazi <addazi.lorenzo@gmail.com>
=> [Quickfix] Add quickfix for empty keywords #994

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractContentAssistTest.xtend, org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractContentAssistTest.java, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/junit/ui/AbstractContentAssistTest.xtend, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/junit/ui/AbstractContentAssistTest.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/AbstractXbaseContentAssistBugTest.xtend, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/hyperlinking/AbstractHyperlinkingTest.xtend, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/editor/AbstractXbaseContentAssistBugTest.java, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/hyperlinking/AbstractHyperlinkingTest.java
mark abstract classes as abstract
do you think this is ok api wise?
=> mark abstract classes as abstract

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextInformationProvider.java
[#977] Cleanup XtextInformationProvider
=> [#977] Cleanup XtextInformationProvider

Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/serializer/AbstractDomainmodelSyntacticSequencer.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/serializer/DomainmodelSyntacticSequencer.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/serializer/DomainmodelSyntacticSequencer.java, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1412] build against 2019-03 release
=> [eclipse/xtext#1412] build against 2019-03 release

org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/contentassist/AbstractPureXbaseProposalProvider.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java
Support Content Proposals of used resources within expression block
Signed-off-by: Eva Poell <epoell@itemis.com>
=> [eclipse/xtext-xtend#395] Try With Resources

org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/contentassist/AbstractPureXbaseProposalProvider.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java
Reverts eclipse/xtext-eclipse#1008
=> Revert "[eclipse/xtext-xtend#395] Try With Resources"

README.md, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> use https to access typefox jenkins

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1412] oomph against 4.11 release and 4.12 I-Builds
=> [eclipse/xtext#1412] oomph against 4.11 release and 4.12 I-Builds

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/BatchModification.java
Using a SubMonitor to report the progress of applying changes and split
the work in proportion (giving 80% for modifications and use remaining
work in the method).
=> [eclipse/xtext#1403] Improve progress feedback

1-maven-build.sh, CBI.Jenkinsfile, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/ContentAssistProcessorTestBuilder.java, org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/RefactoringDocumentProviderTest.java, pom.xml, releng/org.eclipse.xtext.p2-repository/pom.xml
- add Slack notification
- externalize build call to shell script
- Disable p2 mirrors for Tycho
=> [eclipse/xtext#1309] Extend initial Jenkinsfile for CJE

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/BatchModification.java
Prefer SubMonitor#split() instead of #worked(). This also checks already
for cancellation, which makes manual checking obsolete.
=> [eclipse/xtext#1403] Improve progress reporting

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/StratumBreakpointAdapterFactory.java, org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/xtext/ui/RefactoringTest.java, org.eclipse.xtext.purexbase.ui/src/org/eclipse/xtext/purexbase/ui/autoedit/ReplAutoEdit.java, org.eclipse.xtext.ui.codemining/src/org/eclipse/xtext/ui/codemining/AbstractXtextCodeMiningProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DocumentBasedDirtyResource.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/LanguageSpecificURIEditorOpener.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/copyqualifiedname/OutlineCopyQualifiedNameHandler.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/DefaultFoldingRegionProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AbstractEObjectHover.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/DefaultHyperlinkDetector.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/CompositeModificationWrapper.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/MultiModificationWrapper.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/occurrences/DefaultOccurrenceComputer.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/DefaultOutlineTreeProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/DocumentRootNode.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlineNodeElementOpener.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlineNodeFactory.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/DefaultQuickfixProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/HighlightingReconciler.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/ValidationJob.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringController.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/actions/ImportsAwareClipboardAction.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/launching/JavaElementDelegate.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/XbaseQuickfixProvider.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.java, org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/RailroadSynchronizer.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/launcher/SelectionUtil.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Didn't replace any occurrences in tests, also avoided a few uses where it could change behavior.
=> Use tryReadOnly instead of readOnly

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1422] update to tycho 1.4.0
=> [eclipse/xtext#1422] update to tycho 1.4.0

CBI.Jenkinsfile
[eclipse/xtext#1430] added missing tp to CBI
=> [eclipse/xtext#1430] added missing tp to CBI

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/validation/ProjectAwareUniqueClassNameValidatorTest.xtend, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/validation/MockedFile.java, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/validation/MockedProjectAwareUniqueClassNameValidator.java, org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/validation/ProjectAwareUniqueClassNameValidatorTest.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.xtend, org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
=> bogus behaviour of ProjectAwareUniqueClassNameValidator.isDerived #675

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/AbstractHyperlink.java
=> [#1044] AbstractHyperlink: Usage of IRegion instead of Region.

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/DeltaConverter.java
Signed-off-by: Sergio Otero Lopez <sergio.otero@gmail.com>
=> [eclipse/xtext-eclipse#986] BuilderDeltaConverter JDT leak

CBI.Jenkinsfile
=> [eclipse/xtext#1434] Upgrade to xtext-buildenv 0.7

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.java
…more specifically, if a custom resource relocation strategy impl demands for relying on the persisted resource index.
enables the avoidance of heap pollution and resultant performance decrease due to creating the live scope resource descriptions of the affected resources before executing the actual modifications; can easily happen if the amount of files being moved or renamed is too large
=> [refactoring2] modified 'ResourceRelocationProcessor' to switch to the persisted index if required

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ClosedProjectsQueue.java
reduced MAX_ATTEMPTS to a smaller number (10 instead of 100
=> reduced MAX_ATTEMPTS to a smaller number (10 instead of 100)

org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/junit/formatter/FormatterTester.java, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1437] Bootstrap against 2.18.0.M2
=> [eclipse/xtext#1437] Bootstrap against 2.18.0.M2

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/AbstractXtextTests.java, org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/internal/InjectorProviders.java, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler.java, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler2.xtend, org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler2.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.java
fixed deprecations with java 11
=> fixed deprecations with java 11

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java, org.eclipse.xtext.xbase.ui.testing/src/org/eclipse/xtext/xbase/ui/testing/AbstractXbaseContentAssistTest.java
[#1070] fix test failures with java 11
=> [#1070] fix test failures with java 11

CBI.Jenkinsfile, Jenkinsfile
- add Slack notification
- externalize build call to shell script
=> [eclipse/xtext#1384] Convert to Declarative Pipeline

CBI.Jenkinsfile, Jenkinsfile
[eclipse/xtext#1458] fixed casing for target platform variable
=> [eclipse/xtext#1458] fixed casing for target platform variable

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup
=> fixed more https issues

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/IBuilderState.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildData.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/SetWithProjectNames.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
[#1066] Pass all participating projects along with BuildData
=> [#1066] Pass all participating projects along with BuildData

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
[eclipse/xtext#1460] Two phase lock of the workspace in BuilderState.load
=> [eclipse/xtext#1460] Two phase lock of the workspace in BuilderState.load

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java, org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/SharedModule.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/scoping/namespaces/AbstractJavaProjectsStateTest.java, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java, org.eclipse.xtext.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/workspace/WorkspaceLockAccess.java
[#1460] Handle shutdown scenario properly
=> [#1460] Handle shutdown scenario properly

org.eclipse.xtext.doc/contents/302_configuration.html, org.eclipse.xtext.doc/contents/350_continuous_integration.html, org.eclipse.xtext.doc/contents/toc.xml
=> regenerated docs for 2.18 release

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
[eclipse/xtext#1475] build against orbit 2019-09
=> [eclipse/xtext#1475] build against orbit 2019-09

CBI.Jenkinsfile, Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1475] prepared target platform for 2019-09
=> [eclipse/xtext#1475] prepared target platform for 2019-09

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> [eclipse/xtext#1485] update to mwe 2.11

CBI.Jenkinsfile, Jenkinsfile
=> increased timeout cause ci.eclipse.org gets more and more crappy

releng/org.eclipse.xtext.contributor/Xtext.setup
=> fixed broken setup 

releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target
[eclipse/xtext-xtend#818] Add classgraph to target platform
=> [eclipse/xtext-xtend#818] Add classgraph to target platform

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend, org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
=> [#1108] fixed layout issue in 2nd new project page status widget

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
[eclipse/xtext-xtend#818] Add classgraph to domainmodel tp
=> [eclipse/xtext-xtend#818] Add classgraph to domainmodel tp

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext1475] use 2019-09 in latest target platform
=> [eclipse/xtext1475] use 2019-09 in latest target platform

releng/org.eclipse.xtext.contributor/Xtext.setup
=> [eclipse/xtext#1475] prepared oomph for 2019-09

CBI.Jenkinsfile, Jenkinsfile
=> [eclipse/xtext#1465] Use declarative JUnit step

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1497] added egit to target platforms
=> [eclipse/xtext#1497] added egit to target platforms

org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineContentAssistTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.java
=> regenerate with latest xtend

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
[#1132] marked workbench as nullable
=> [#1132] marked workbench as nullable

org.eclipse.xtext.builder.tests/xtext.builder.tests.fast.launch, org.eclipse.xtext.builder.tests/xtext.builder.tests.nojdt.launch, org.eclipse.xtext.common.types.eclipse.tests/xtext.common.types.eclipse.tests.launch, org.eclipse.xtext.eclipse.tests/xtext.eclipse.tests (xtend).launch, org.eclipse.xtext.eclipse.tests/xtext.eclipse.tests.launch, org.eclipse.xtext.ui.tests/xtext.ui.tests.fast (xtend).launch, org.eclipse.xtext.ui.tests/xtext.ui.tests.fast.launch, org.eclipse.xtext.ui.tests/xtext.ui.tests.slow.launch, org.eclipse.xtext.xbase.ui.tests/xtext.xbase.ui.tests (xtend).launch, org.eclipse.xtext.xbase.ui.tests/xtext.xbase.ui.tests.fast.launch, org.eclipse.xtext.xbase.ui.tests/xtext.xbase.ui.tests.slow.launch, org.eclipse.xtext.xtext.ui.tests/xtext.xtext.ui.tests.fast.launch, org.eclipse.xtext.xtext.ui.tests/xtext.xtext.ui.tests.slow.launch
=> removed ancient relics from launch configs

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/ui/notification/TypeResourceUnloaderTest.java
=> Remove unused import from the TypeResourceUnloaderTest class.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/workspace/EclipseProjectConfig.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/workspace/EclipseProjectConfig.java
see https://github.com/eclipse/xtext-core/pull/1209
=> Extend IProjectConfig and related interfaces

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DocumentBasedDirtyResource.java
[#1139] added better locking to document based dirty resource
=> [#1139] added better locking to document based dirty resource

releng/org.eclipse.xtext.contributor/Xtext.setup
=> [eclipse/xtext-umbrella#140] enabled formatter on/off tags

CBI.Jenkinsfile, Jenkinsfile
[eclipse/xtext#1513] Add nightly master-trigger to replace trigger job
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> [eclipse/xtext#1513] Add nightly master-trigger to replace trigger job

org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/bracketmatching/services/BmTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/BacktrackingContentAssistTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug287941TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug291022TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug303200TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug304681TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug309949TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug332217TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348199TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348427TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug360834TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug381381TestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ContentAssistCustomizingTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/LookAheadContentAssistTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParameterizedExpressionsTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParametersTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/TwoParametersTestLanguageGrammarAccess.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlContentAssistLexer.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlHighlightingLexer.java, org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlRuntimeLexer.java, org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/GenerateTestLanguages.mwe2
[#1161] ExternalAntlrGeneratorFragment produces consistent output
=> [#1161] ExternalAntlrGeneratorFragment produces consistent output

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> preserve parameter names during compilation with tycho

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/XtextInjectorProvider.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/hierarchy/XtextCallHierarchyBuilderTest.xtend, org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/hierarchy/XtextCallHierarchyBuilderTest.java
=> prepared gradle update by decoupling from xtext.tests

org.eclipse.xtext.doc/contents/350_continuous_integration.html
=> regenerated help pages

releng/org.eclipse.xtext.contributor/Xtext.setup
=> fixed broken junit 5 version in oomph setup

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> bootstrap against m3

Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1538] created 2019-09 target
=> [eclipse/xtext#1538] created 2019-09 target

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/util/JarPackageFragmentRootTestUtil.java, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1538] use 4.14 I-Builds repo in latest
=> [eclipse/xtext#1538] use 4.14 I-Builds repo in latest

Jenkinsfile
sort target platform options chronologically
=> sort target platform options chronologically

releng/org.eclipse.xtext.contributor/Xtext.setup
=> [eclipse/xtext#1538] prepared 2019-12 oomph

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.java
=> Domainmodel Example: Add property and operation template proposal tests.

org.eclipse.xtext.xbase.ui.testing/src/org/eclipse/xtext/xbase/ui/testing/AbstractXbaseContentAssistTest.java
[eclipse/xtext-eclipse#1182] fixed some test fails with java 13
=> [eclipse/xtext-eclipse#1182] fixed some test fails with java 13

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/src/org/eclipse/xtext/example/arithmetics/tests/ArithmeticsParsingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/src/org/eclipse/xtext/example/arithmetics/tests/interpreter/CalculatorTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/tests/ArithmeticsParsingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/tests/interpreter/CalculatorTest.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/src/org/eclipse/xtext/example/arithmetics/ui/tests/autoedit/AutoEditTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/tests/autoedit/AutoEditTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/DomainmodelParsingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/DomainmodelParsingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/FoldingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/LabelProviderTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/src/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineFormatterTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/ModelTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/RuleEngineParsingTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/ValidationTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/ModelTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/RuleEngineParsingTest.java, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/xtend-gen/org/eclipse/xtext/example/homeautomation/tests/ValidationTest.java
- Provide more compact and readable test code by utilizing Xtend
capabilities.
=> Xtext Examples: Refactoring the test cases.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java
- Readability improvements, no functional changes.
=> Domainmodel Example: Refactoring Validator/Formatter Xtend code.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target
[eclipse/xtext#1538] use orbit 2019-12
=> [eclipse/xtext#1538] use orbit 2019-12

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
added xtext.logging to extra requirements
=> added xtext.logging to extra requirements

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
[#1171] better management of xtext version
=> [#1171] better management of xtext version

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/IssueCodes.java, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java
I started to work on this, starting from the current PR https://github.com/eclipse/xtext-eclipse/pull/1203
I'm planning to add some further tests, but some initial feedback would be helpful :)
Closes #1205
=> [#1205] Domainmodel example: Add duplicated operation validation rule.

org.eclipse.xtext.common.types.shared.jdt38/fragment.properties, org.eclipse.xtext.common.types.shared/plugin.properties
[#529759] more consistent bundle names
=> [#529759] more consistent bundle names

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/META-INF/MANIFEST.MF
=> Xtext Example: Use consistent Bundle-Names.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractTemplate.java
- Eliminate duplicated code in the text, check, combo and group methods.
=> Refactoring the AbstractTemplate class.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1553] update to tycho 1.5.0
=> [eclipse/xtext#1553] update to tycho 1.5.0

org.eclipse.xtext.doc/contents/103_domainmodelnextsteps.html, org.eclipse.xtext.doc/contents/303_runtime_concepts.html, org.eclipse.xtext.doc/contents/310_eclipse_support.html
update docs from website-master
=> update docs from website-master

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/JavaProjectResourceSetInitializer.java
added option to skip legacy platform uri map calculation
=> added option to skip legacy platform uri map calculation

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.20.0.M2

org.eclipse.xtext.builder.tests/xtext.standalone.builder.junit.launch
This change was automatically applied by the tooling after setup of a
fresh workspace.
=> [eclipse/xtext#1568] Formatting: Added indentation

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextUiModule.java
make sure xtext.xtext.ui can be activated without xpand/xtend1 present
=> make sure xtext.xtext.ui can be activated without xpand/xtend1 present

org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.java
regenerated with latest xbase.lib
=> regenerated with latest xbase.lib

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/GenerateStatemachine.mwe2, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/GenerateRuleEngine.mwe2
=> fixed broken config of formatter fragment

org.eclipse.xtext.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/.classpath
=> fixed errors in ui.tests due accessrule not working properly

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/.classpath
=> [#1259] Fix invalid fowlerdsl.ui classpath.

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
The EGit IndexDiffUpdateJob interrupted Xtext builds, which made the
workaround necessary. EGit was fixed with Eclipse Mars, which is below
minimum target requirement now. This makes the workaround obsolete.
=> [#251] Remove workaround for bug#474003

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1609] update to mwe 2.11.1
=> [eclipse/xtext#1609] update to mwe 2.11.1

releng/org.eclipse.xtext.contributor/Xtext.setup
[#1261] removed maintenance stream
=> [#1261] removed maintenance stream

org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/TestLanguagesFragments.mwe2, org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/TestLanguagesFragmentsWithConversionTimeout.mwe2
=> fixed deprecations

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/AbstractResourceLoader.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ParallelResourceLoader.java
made load operation public to allow easier subclassing
=> made load operation public to allow easier subclassing

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.20.0.M3

Jenkinsfile, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1603] create target for r201912
=> [eclipse/xtext#1603] create target for r201912

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.20.0

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/META-INF/MANIFEST.MF
- Sort the 'Import-Package' entries lexicographically ascending to
enable a better comparison between them.
=> Cleaning up the Xtext Examples MANIFEST.MF files.

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/MockJavaProjectProvider.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JREContainerProvider.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/AbstractXbaseUITestCase.java
change default bree/complicance
=> change default bree/complicance

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java
Use it from original Xtend file if Messages.java does not yet exist.
Maintain existing file comment if Messages.java already exist.
=> [#1228] Handle file comment in 'Messages.java'.

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1604] updated to 2020-03 simrel update site
=> [eclipse/xtext#1604] updated to 2020-03 simrel update site

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
=> use 2020-03 in domain model example

releng/org.eclipse.xtext.contributor/Xtext.setup
=> go back to orbit 2020-03

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target
[eclipse/xtext#1605] update orbit to 2020-03
=> [eclipse/xtext#1605] update orbit to 2020-03

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java
pass possible cause in all cases
=> pass possible cause in all cases

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/Messages.java
=> [#1228] Statemachine example: Regenerate the Messages.java class.

org.eclipse.xtext.builder/xtend-gen/org/eclipse/xtext/builder/debug/IBuildLogger.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/rename/ISimpleNameProvider.java
[eclipse/xtext#1642] regenerated xtend code with latest xtend
=> [eclipse/xtext#1642] regenerated xtend code with latest xtend

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.21.0.M1

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/search/IteratorJob.java
improved clustering in IteratorJob (Open Model Element Dialog)
=> improved clustering in IteratorJob (Open Model Element Dialog)

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewPage.java
Signed-off-by: David Medina <david.medina@sigasi.com>
=> Removed deprecated API and fixed a warning

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1643] update to tycho 1.6.0
=> [eclipse/xtext#1643] update to tycho 1.6.0

releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
removed duplicate extra requirement
=> removed duplicate extra requirement

org.eclipse.xtext.m2e/lifecycle-mapping-metadata.xml
Signed-off-by: jrosczak <jan.rosczak@web.de>
=> [eclipse/xtext-maven#111] Add testGenerate goal to lifecycle mapping

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target
=> use junit 4.12 explicitely

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.21.0.M2

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/EditorDocumentUndoChange.java
=> Fixed Editor Search in UNDO

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/AbstractPluginProjectCreator.java
removed old gen & xpand from AbstractPluginProjectCreator
=> removed old gen & xpand from AbstractPluginProjectCreator

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> test with MWE 2.11.2.M3

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1641] fixed junit5 in oomph
=> [eclipse/xtext#1641] fixed junit5 in oomph

releng/org.eclipse.xtext.contributor/Xtext.setup
update oomph to lsp4j 0.9.0 M3
=> update oomph to lsp4j 0.9.0 M3

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-umbrella#202] workaround for egit oomph problem
=> [eclipse/xtext-umbrella#202] workaround for egit oomph problem

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.21.0.M3

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1673] udpate to MWE 2.11.2
=> [eclipse/xtext#1673] udpate to MWE 2.11.2

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/IBuildLogger.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/BuilderDeltaConverter.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/autoedit/AutoEditStrategy.java
=> fixed unused imports

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.21.0

org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/FileTemplate.java, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/ProjectTemplate.java
=> regenerated xtend code

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1686] prepared R2020-03 release target platform
=> [eclipse/xtext#1686] prepared R2020-03 release target platform

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1685] use 2020-06 update site
=> [eclipse/xtext#1685] use 2020-06 update site

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1681] prepared oomph for 2020-06
=> [eclipse/xtext#1681] prepared oomph for 2020-06

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend, org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java
=> made tests java 14 ready

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target
[eclipse/xtext#1682] update orbit to 2020-06
=> [eclipse/xtext#1682] update orbit to 2020-06

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.java
restored old api of SingleHoverShowingHyperlinkPresenter
=> restored old api of SingleHoverShowingHyperlinkPresenter

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.xtend, org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java
- in the generated messages.properties file.
=> [#1433] New Project / New File Wizard. Fix incorrect newline handling.

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/codemining/ArithmeticsCodeMiningProvider.java, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2
=> [#1330] Add CodeMining to the Xtext Arithmetics example.

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ClosedProjectsQueue.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
[#1383] No poll at clean + api for ClosedProjectsQueue
=> No poll at clean + api for ClosedProjectsQueue

org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.builder.tests/build.properties, org.eclipse.xtext.eclipse.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.eclipse.tests/build.properties
clean manifests regarding generator dependency
=> clean manifests regarding generator dependency

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/bracketmatching/BracePairMatcher.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/JvmAnnotationReferencePrinter.java
fixed more migration regressions
=> fixed more migration regressions

org.eclipse.xtext.doc/contents/102_domainmodelwalkthrough.html, org.eclipse.xtext.doc/contents/103_domainmodelnextsteps.html
=> regen docs

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.22.0.M1

org.eclipse.xtext.xtext.ui.examples/pom.xml, releng/org.eclipse.xtext.p2-repository/pom.xml
=> [https://github.com/eclipse/xtext/issues/1742] Update

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/navigation/NavigationService.java
=> fixed x2j migration fallout

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractFoldingTest.java
=> fixed more fallout

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java
=> Fix potential null pointer access in the AdvancedNewProjectPage class.

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.22.0.M2

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java
=> [#1435] Remove listener from index when content provider is disposed

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1765] update to MWE 2.11.3.M3
=> [eclipse/xtext#1765] update to MWE 2.11.3.M3

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.java
=> [#1221] Update Xtext Domainmodel example QuickfixTest test cases.

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/messages.properties
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> Streamline BuildScheduler_ManyJobsName message text

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateManager.java
=> [eclipse/xtext-core#1466] Send proper events for dirty state changes

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/JavaBuilderState.java
[#1450] adapted JavaBuilderState to change in field type of State.references
=> [#1450] adapted JavaBuilderState to change in field type of State.references

org.eclipse.xtext.purexbase.ui/plugin.xml, org.eclipse.xtext.purexbase.ui/plugin.xml_gen, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/plugin.xml
- Regenerate plugin.xml_gen.
- Merge plugin.xml_gen into plugin.xml.
=> Regenerate Xtext Test Languages, Examples, PureXbase.

org.eclipse.xtext.doc/contents/350_continuous_integration.html, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1770] update to mwe 2.11.3 final
=> [eclipse/xtext#1770] update to mwe 2.11.3 final

org.eclipse.xtext.builder.tests/plugin.xml, org.eclipse.xtext.builder.tests/plugin.xml_gen, org.eclipse.xtext.common.types.eclipse.tests/plugin.xml, org.eclipse.xtext.common.types.eclipse.tests/plugin.xml_gen, org.eclipse.xtext.purexbase.ui/plugin.xml, org.eclipse.xtext.purexbase.ui/plugin.xml_gen, org.eclipse.xtext.testlanguages.ui/plugin.xml, org.eclipse.xtext.testlanguages.ui/plugin.xml_gen, org.eclipse.xtext.ui.codetemplates.ui/plugin.xml, org.eclipse.xtext.ui.codetemplates.ui/plugin.xml_gen, org.eclipse.xtext.xbase.testlanguages.ui/plugin.xml, org.eclipse.xtext.xbase.testlanguages.ui/plugin.xml_gen, org.eclipse.xtext.xbase.ui/plugin.xml, org.eclipse.xtext.xbase.ui/plugin.xml_gen, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/plugin.xml, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/plugin.xml, org.eclipse.xtext.xtext.ui.tests/plugin.xml, org.eclipse.xtext.xtext.ui.tests/plugin.xml_gen
- Regenerate plugin.xml_gen.
- Merge plugin.xml_gen into plugin.xml.
=> Regenerate Xtext Test Languages, CodeTemplates, Examples, PureXbase.

org.eclipse.xtext.ui.tests/plugin.xml, org.eclipse.xtext.ui.tests/plugin.xml_gen
- Regenerate plugin.xml_gen.
- Merge plugin.xml_gen into plugin.xml.
=> Regenerate Xtext UI Test Languages.

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.22.0.M3

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.22.0

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1785] created r202006 tp
=> [eclipse/xtext#1785] created r202006 tp

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/formatting2/StatemachineFormatter.xtend
avoid extension use of Strings.repeat
=> avoid extension use of Strings.repeat

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target
[eclipse/xtext#1781] update orbit to 2020-09
=> [eclipse/xtext#1781] update orbit to 2020-09

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/RegistryBuilderParticipant.java
[#1476] added check for cancellation during last participant
=> [#1476] added check for cancellation during last participant

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1780] prepare oomph for 2020-09
=> [eclipse/xtext#1780] prepare oomph for 2020-09

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/TemplatePositionUpdater.java
=> [#1484] Make TemplatePositionUpdater public

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java
fixed validation problem with stale/broken java index
=> fixed validation problem with stale/broken java index

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Signed-off-by: nbhusare <neerajbhusare@gmail.com>
=> Add new Xtext editor quickfixes on *.xtext files

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.23.0.M1

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
[#1494] fixed race condition on loading the Xtext index from multiple threads
=> [#1494] fixed race condition on loading the Xtext index from multiple threads

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target
[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0
=> [eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF
=> fixed warning

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.23.0.M2

Jenkinsfile
=> always archive ui test logs

org.eclipse.xtext.common.types.shared.jdt38/.classpath
=> fixed outdated .classpath

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/JdtToBeBuiltComputer.java
made JdtToBeBuiltComputer.shouldHandle customizable
=> made JdtToBeBuiltComputer.shouldHandle customizable

Jenkinsfile
run tests with java 11 (provisional fix)
=> run tests with java 11 (provisional fix)

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractWorkbenchTest.java
process ui events after test to avoid memory leak in tests
=> process ui events after test to avoid memory leak in tests

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.23.0.M3

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.23.0

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/label/DefaultEObjectLabelProviderTest.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/ParameterContextInformation.java, org.eclipse.xtext.xtext.ui.examples/projects/xbase.tutorial/src/helper/Amount.java
fixed warnings when compiling against Java 11
=> fixed warnings when compiling against Java 11

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/handler/ValidateActionHandler.java
[#1463] fixed handling of fast check issues in validate action
=> [#1463] fixed handling of fast check issues in validate action

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
=> fixed tycho version var

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target
=> fixed emf version in r202006

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1831] update latest to 4.18-I-builds
=> [eclipse/xtext#1831] update latest to 4.18-I-builds

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1832] create r202009 target
=> [eclipse/xtext#1832] create r202009 target

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target
[eclipse/xtext#1828] update orbit to 2020-12
=> [eclipse/xtext#1828] update orbit to 2020-12

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12
=> [eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12

releng/org.eclipse.xtext.contributor/Xtext.setup
changed default tp in oomph to latest
=> changed default tp in oomph to latest

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/XtextDocumentModifyTest.java
=> [#1539] Use system line endings.

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/SourceBasedJdtTypeProviderTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/refactoring/RefactoringCrossReferenceSerializerTest.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseEditor.java
[eclipse/xtext#1850] Fix resource leaks
=> [eclipse/xtext#1850] Fix resource leaks

org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
Use System specific line separator
Fixes #1539
=> Use System specific line separator

releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target
=> [eclipse/xtext#1851] Add more Junit5 bundles to TP

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.24.0.M1

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RefactoringUIMessages.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringPopup.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/messages.properties
Localization for rename refactoring hint added
see #1555
=> [eclipse/xtext-eclipse#1555] Localization for rename refactoring hint

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
=> fixed spotbugs bugs

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/DefaultUiModule.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/validation/AbstractValidatorConfigurationBlock.java
fix javadoc & warning for platform refactoring
=> fix javadoc & warning for platform refactoring

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/TemporaryFolder.java
=> fix temp folder security flaw

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractCodeMiningTest.java
[#1563] Fixed Line Header Code Minings at Pos 0,0
Fixes: #1563
=> [#1563] Fixed Line Header Code Minings at Pos 0,0

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/templates/XtextTemplateStore.java
This getter avoids large scale  copy and paste of the class
Signed-off-by: Srinivas Iyer <srinivasiyermv@gmail.com>
=> [eclipse/xtext-eclipse#1561]:Added getter for resource variable

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1855] update to junit 5.7
=> [eclipse/xtext#1855] update to junit 5.7

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/XbaseUIValidator.java
[eclipse/xtext-xtend#1132] do restriction checks also on type literal member feature calls
=> [eclipse/xtext-xtend#1132] do restriction checks also on type literal member feature calls

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2
=> [eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/WorkspaceFileGenerator.java
Added the encoding to the StingInputStream
=> [#1566] set encoding to StringInputStream

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.24.0.M2

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
This makes it easier to replace the version with sed for bot updates.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> Define MWE2 version by property

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1566] update to LSP4J 0.10.0
=> [eclipse/xtext-core#1566] update to LSP4J 0.10.0

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/PreferenceStoreAccessor.java
- typo in 'backgroun'
- change suffix 'DefaultDefault' to 'SystemDefault'
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [trivial] Variable renaming

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/AbstractTextEditComposerTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/ChangeSerializerComposerTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/XtextDocumentModifyTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextUiModule.java
Not yet complete. Wait with merging before everything is done. But can be already reviewed to a certain degree.
=> Java based formatter2 API and Xtext formatter

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> [releng] Update MWE to 1.6.0/2.12.0

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.24.0.M3

org.eclipse.xtext.doc/contents/304_ide_concepts.html, org.eclipse.xtext.doc/contents/310_web_integration.html, org.eclipse.xtext.doc/contents/350_continuous_integration.html, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/util/BundleClasspathUriResolverTest.java
regen docs & fix unused imports
=> regen docs & fix unused imports

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.24.0

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1886] created r202012 target platform
=> [eclipse/xtext#1886] created r202012 target platform

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target
[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet
=> [eclipse/xtext#1882][2021-03] Update Orbit

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1885] use 2021-03 in latest tp
DO NOT merge yet, 2021-03 is not available yet
=> [eclipse/xtext#1885] use 2021-03 in latest tp

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1881] prepare oomph for 2021-03
=> [eclipse/xtext#1881] prepare oomph for 2021-03

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.25.0.M1

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ClipboardUtil.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/IProjectCreator.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseEditor.java
Signed-off-by: miklossy <miklossy@itemis.de>
=> Fixing typos in the javadoc comments.

Jenkinsfile
[eclipse/xtext#1737] archive eclipse test logs also on success
=> [eclipse/xtext#1737] archive eclipse test logs also on success

org.eclipse.xtext.doc/contents/350_continuous_integration.html, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1925] update to MWE 2.12.1.M2
=> [eclipse/xtext#1925] update to MWE 2.12.1.M2

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.25.0.M2

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractFileTemplate.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractProjectTemplate.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/NewFileWizardPrimaryPage.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateNewFileWizard.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateNewProjectWizard.java
=> [#1610] Relax API restrictions to ease extensibility.

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/templates/DefaultTemplateProposalProvider.java
=> [#1622] Use plugin image registry to avoid leak.

org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/editor/EditorForAbsentFileTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewer.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
Signed-off-by: Sebastian Zarnekow <sebastian.zarnekow@gmail.com>
=> [#1627] Handle now-missing files more gracefully

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/trace/TraceEditor.java
=> [#464] Set selection and create copy context menu.

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final
=> [eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.25.0.M3

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.25.0

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1948] create r202103 target platform
=> [eclipse/xtext#1948] create r202103 target platform

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistCatchTest.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistDoWhileTest.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistInIfThenTest.java, org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistTryTest.java
=> cleanup tests

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/JdtQueuedBuildData.java
[571671] optimize JdtQueuedBuildData.doNeedRebuild
=> [571671] optimize JdtQueuedBuildData.doNeedRebuild

Jenkinsfile, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1947] update to 4.20-I-builds
=> [eclipse/xtext#1947] update to 4.20-I-builds

releng/org.eclipse.xtext.contributor/Xtext.setup
use m2e version from 2021-03 release
=> use m2e version from 2021-03 release

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target
[eclipse/xtext#1944] update orbit to 2021-06
=> [eclipse/xtext#1944] update orbit to 2021-06

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target
=> use explicit guice version

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
=> fix tests on java 15

releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1960]use tycho 2.2 on latest
=> [eclipse/xtext#1960]use tycho 2.2 on latest

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#1947] adapt tps for 2021-06
=> [eclipse/xtext#1947] adapt tps for 2021-06

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#1943] prepare oomph for 2021-06
=> [eclipse/xtext#1943] prepare oomph for 2021-06

Jenkinsfile
=> increased timeout to 5 hrs

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
make Storage2UriMapperJavaImpl better customizable
=> make Storage2UriMapperJavaImpl better customizable

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
=> use tycho 2.3 in domain model

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
revert use of staging in domain model
=> revert use of staging in domain model

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
bump exec-maven-plugin to 3.0.0
=> bump exec-maven-plugin to 3.0.0

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.26.0.M1

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuilderStateDiscarder.java
[#1671]always run in job to avoid deadlock and check accessibility in job
=> [#1671]always run in job to avoid deadlock and check accessibility in job

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> prepare 2021-06 release tp

Jenkinsfile, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
build latest against 4.21-I-builds
=> build latest against 4.21-I-builds

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target
=> update to orbit 2021-09

releng/org.eclipse.xtext.contributor/Xtext.setup
=> update to orbit 2021-09 in oomph

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
use eclipse 2021-09 in target platform
DO NOT MERGE YET
=> use eclipse 2021-09 in target platform

releng/org.eclipse.xtext.contributor/Xtext.setup
=> update oomph for 2021-09 

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineProjectTemplateProvider.xtend, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/MrsGrantsSecretCompartmentsProject.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineProjectTemplateProvider.java
dont use new for PluginImageHelper
see #1689
=> dont use new for PluginImageHelper

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
=> Fix writing of past tense of "build"

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> update to tycho 2.4

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java
[#1701] better progress reporting for queueAffectedResources
=> [#1701] better progress reporting for queueAffectedResources

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
Adapt Lifecycle Mappings to changes in tycho
See https://github.com/itemis/xtext-reference-projects/issues/194
=> Adapt Lifecycle Mappings to changes in tycho

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
dont duplicate deps. that are already part of add. bundles in build.properties
=> dont duplicate deps. that are already part of add. bundles in build.properties

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/PluginImageHelper.java
Dispose images in PluginImageHelper when Display is disposed
Fixes #1703
=> Dispose images in PluginImageHelper when Display is disposed

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ParallelResourceLoader.java
=> name parallel loader pool

org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/Messages.java, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/messages.properties
fixed broken example aa generates
=> fixed broken example aa generates

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/antlr/DelegatingContentAssistContextFactoryWithSharedPool.java
=> shared pool for cacf

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/resourceloader/ParallelResourceLoader.java
=> open up ParallelLoadOperation

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> use MWE2 2.12.2.M1

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java
[#1490] Fix DirtyStateEditorSupportIntegrationTest on Mac
=> [#1490] Fix DirtyStateEditorSupportIntegrationTest on Mac

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> added target for 2021-09

org.eclipse.xtext.doc/contents/304_ide_concepts.html, org.eclipse.xtext.doc/contents/310_web_integration.html, org.eclipse.xtext.doc/contents/350_continuous_integration.html
regenerated docs from website-master
=> regenerated docs from website-master

Jenkinsfile, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> update to 4.22 for latest

releng/org.eclipse.xtext.contributor/Xtext.setup
do not merge before oomph and eclipse are ready
=> oomph update r202109

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> use 2021-12 in latest

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#1994] update to tycho 2.5.0
=> [eclipse/xtext#1994] update to tycho 2.5.0

releng/org.eclipse.xtext.contributor/Xtext.setup
=> dropped non legacy gef

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextResourceMarkerAnnotationModel.java
Update the "connected" property on disconnection
=> Update the "connected" property on disconnection

releng/org.eclipse.xtext.contributor/Xtext.setup
=> prepare 2022-03 oomph

org.eclipse.xtext.buildship/META-INF/MANIFEST.MF, org.eclipse.xtext.buildship/src/org/eclipse/xtext/buildship/IgnoreBuildDirContribution.java
[#1760] persist gradle build dir on project to survive restarts
=> [#1760] persist gradle build dir on project to survive restarts

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
[eclipse/xtext#2020]consume classgraph from Xtext
=> [eclipse/xtext#2020]consume classgraph from Xtext

NOTICE.md, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target
[eclipse/xtext#2020] update to classgraph 4.8.138
=> [eclipse/xtext#2020] update to classgraph 4.8.138

org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/descriptions/ClasspathScannerTest.java
[eclipse/xtext#2020] added test for classgraph in eclipse
=> [eclipse/xtext#2020] added test for classgraph in eclipse

releng/org.eclipse.xtext.contributor/Xtext.setup
=> switch to https

org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/AbstractXbaseWithAnnotationsUiModule.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/XbaseWithAnnotationsExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/contentassist/AbstractXbaseWithAnnotationsProposalProvider.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/annotations/ui/editor/XbaseWithAnnotationsEditor.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/AbstractXbaseUiModule.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/AbstractXtypeUiModule.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/XbaseExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/XtypeExecutableExtensionFactory.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/contentassist/AbstractXbaseProposalProvider.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/contentassist/AbstractXtypeProposalProvider.java, org.eclipse.xtext.xbase.ui/src-gen/org/eclipse/xtext/xbase/ui/internal/XbaseActivator.java
=> regenerated xbase

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release
=> [eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2021] update to tycho 2.6.0
=> [eclipse/xtext#2021] update to tycho 2.6.0

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.26.0.M3

org.eclipse.xtext.logging/META-INF/MANIFEST.MF
=> [eclipse/xtext#2028] widen version range for log4j fragment

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/occurrences/OccurrenceMarker.java
[#1776] fix MarkOccurrencesTest
=> [#1776] fix MarkOccurrencesTest

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
=> switch to 2022-03

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target
[eclipse/xtext#2029] update to orbit 2022-03
=> [eclipse/xtext#2029] update to orbit 2022-03

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> update to 2022-03

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> bumped maven deps

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
fix domainmodel log4j dependency
=> fix domainmodel log4j dependency

Jenkinsfile, releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
add explicit timeout to tests in hope we will get a stacktrace
=> add explicit timeout to tests in hope we will get a stacktrace

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/GenerateDomainmodel.mwe2.launch, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/GenerateStatemachine.mwe2.launch
=> fix example launches

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.26.0.RC1

releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
=> lower xmx for tests

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> [releng] Bootstrap against 2.26.0

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2038] prepare r202203 target
=> [eclipse/xtext#2038] prepare r202203 target

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
=> restrict domainmodel xmx

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target
=> update to emf 2.29

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2038] build against 2.24-I-builds on latest
=> [eclipse/xtext#2038] build against 2.24-I-builds on latest

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
better version of needsRebuild feature
=> better version of needsRebuild feature

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
[eclipse/xtext#2038] use 2022-06 in domainmodel example
=> [eclipse/xtext#2038] use 2022-06 in domainmodel example

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#2038] repare oomph for 2022-06
=> [eclipse/xtext#2038] repare oomph for 2022-06

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/IXtextBuilderParticipant.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/ParallelBuilderParticipant.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
[eclipse/xtext-eclipse#1820] request rebuild on the project files were generated to
=> [eclipse/xtext-eclipse#1820] request rebuild on the project files were generated to

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java
[eclipse/xtext-eclipse#1820] request rebuild on the project files were generated to (2nd attempt)
=> [eclipse/xtext-eclipse#1820] request rebuild on the project files were generated to (2nd attempt)

releng/org.eclipse.xtext.tycho.parent/pom.xml
remove obsolete xtend-maven-plugin
=> remove obsolete xtend-maven-plugin

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
=> bump apache.commons.cli

org.eclipse.xtext.xtext.ui.examples/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
bump maven-clean-plugin from 3.0.0 to 3.2.0
=> bump maven-clean-plugin from 3.0.0 to 3.2.0

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/JdtQueuedBuildData.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/UnconfirmedStructuralChangesDelta.java, org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/DeltaConverter.java
[eclipse/xtext-eclipse#1820] jdtqueuedbuilddataexperiments
=> [eclipse/xtext-eclipse#1820] jdtqueuedbuilddataexperiments

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1
=> [eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> update to tycho 2.7.1

org.eclipse.xtext.xtext.ui.examples/pom.xml, releng/org.eclipse.xtext.p2-repository/pom.xml
=> bumped maven antrun plugin

1-maven-build.sh
[eclipse/xtext-eclipse#1842] remove test failure ignore
=> [eclipse/xtext-eclipse#1842] remove test failure ignore

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target
[eclipse/xtext#2055]simplify dependencies to asm
=> [eclipse/xtext#2055]simplify dependencies to asm

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
=> update to MWE 2.13.0.M2

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2060] update to tycho 2.7.2
=> [eclipse/xtext#2060] update to tycho 2.7.2

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
getStorages used to perform unnecessary expensive exist() checks on
IPackageFragmentRoot and loop the package fragments twice
Signed-off-by: Sebastian Zarnekow <sebastian.zarnekow@gmail.com>
=> [xtext-eclipse#1849] Improve performance of Storage2UriMapperJavaImpl

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2064] update to tycho 2.7.3
=> [eclipse/xtext#2064] update to tycho 2.7.3

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
make creation of packagefragmentrootdata more easily customizable
=> make creation of packagefragmentrootdata more easily customizable

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release
=> [eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1793]  update to lsp4j 0.13.0
=> [eclipse/xtext-core#1793]  update to lsp4j 0.13.0

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1902] update to LSP4J 0.14.0
=> [eclipse/xtext-core#1902] update to LSP4J 0.14.0

Jenkinsfile, org.eclipse.xtext.buildship/pom.xml, org.eclipse.xtext.ui.codemining/pom.xml, org.eclipse.xtext.ui.testing/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2068] prepare r202206 target
=> [eclipse/xtext#2068] prepare r202206 target

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target
[eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature
=> [eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature

releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
[eclipse/xtext-xtend#1355] configure tests to include xtext logging
=> [eclipse/xtext-xtend#1355] configure tests to include xtext logging

releng/org.eclipse.xtext.contributor/Xtext.setup
[#1864] switch to new gef-classic
=> [#1864] switch to new gef-classic

org.eclipse.xtext.builder/deprecated/org/eclipse/xtext/builder/JavaProjectBasedBuilderParticipant.java
adapted to needRebuild changes in platform
=> adapted to needRebuild changes in platform

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
=> update to tycho 2.7.4

NOTICE.md, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target
[eclipse/xtext#2071] update to orbit 2022-09
=> [eclipse/xtext#2071] update to orbit 2022-09

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/pom.xml
bumped maven-dependency-plugin
=> bumped maven-dependency-plugin

releng/org.eclipse.xtext.contributor/Xtext.setup
drop removed org.eclipse.pde.api.tools.ee.feature
https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/194644
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/338
https://github.com/eclipse-pde/eclipse.pde/issues/102
=> drop removed org.eclipse.pde.api.tools.ee.feature

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/pom.xml, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
=> dont override managed version

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
Make loading of Xtext index better hookable
=> Make loading of Xtext index better hookable

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.feature.parent/pom.xml
[eclipse/xtext#2083] use new way for source features in tycho 2.7.x+ builds
=> [eclipse/xtext#2083] use new way for source features in tycho 2.7.x+ builds

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1904] update to lsp4j 0.15.0
=> [eclipse/xtext-core#1904] update to lsp4j 0.15.0

Jenkinsfile, org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/XtextProjectConfigurator.java
m2e: use reflection also for old method
=> m2e: use reflection also for old method

releng/org.eclipse.xtext.contributor/Xtext.setup
[#1895] use M2E 2.0.1 in 2022-09 oomph
=> [#1895] use M2E 2.0.1 in 2022-09 oomph

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2092] switch latest to 4.26 i-builds
=> [eclipse/xtext#2092] switch latest to 4.26 i-builds

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2096] update to tycho 2.7.5
=> [eclipse/xtext#2096] update to tycho 2.7.5

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2092] update to 2022-12 in domainmodel & latest
=> [eclipse/xtext#2092] update to 2022-12 in domainmodel & latest

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext#2092] repare oomph for 2022-12
=> [eclipse/xtext#2092] repare oomph for 2022-12

NOTICE.md, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.contributor/Xtext.setup, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201909.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201912.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202003.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202006.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202009.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202012.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202103.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202106.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202109.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202112.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target
[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
=> [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

org.eclipse.xtext.builder.tests/src-standalone/org/eclipse/xtext/builder/standalone/StandaloneBuilderTest.java
[eclipse/xtext-extras#814] fix broken test expectations
=> [eclipse/xtext-extras#814] fix broken test expectations

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1943] update to lsp4j 0.16.0
=> [eclipse/xtext-core#1943] update to lsp4j 0.16.0

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1986]update to lsp4j 0.17.0
=> [eclipse/xtext-core#1986]update to lsp4j 0.17.0

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
add apache.commons.logging needed by batik needed by platform
=> add apache.commons.logging needed by batik needed by platform

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2106] Update to MWE 2.14.0.M1
=> [eclipse/xtext#2106] Update to MWE 2.14.0.M1

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target
use fixed asm 9.4 version from orbit m3
=> use fixed asm 9.4 version from orbit m3

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#1993] update to lsp4j 0.18.0
=>  [eclipse/xtext-core#1993] update to lsp4j 0.18.0

releng/org.eclipse.xtext.tycho.parent/pom.xml
=> use tycho 2.7.5 everywhere

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target
[eclipse/xtext#2112] Fix Orbit signing problem
=> [eclipse/xtext#2112] Fix Orbit signing problem

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
[eclipse/xtext#2112] switch back to orbit 2022-12 dm
=> [eclipse/xtext#2112] switch back to orbit 2022-12 dm

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target
[eclipse/xtext#2112] switch back to orbit 2022-12
=> [eclipse/xtext#2112] switch back to orbit 2022-12

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2107] update to mwe 2.14.0 release
=> [eclipse/xtext#2107] update to mwe 2.14.0 release

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#2004] Update to lsp4j 0.19.0
=> [eclipse/xtext-core#2004] Update to lsp4j 0.19.0

org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
replace File.createTempFile with Files.createTempFile.toFile
=> replace File.createTempFile with Files.createTempFile.toFile

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/JdtHoverDocumentationProvider.java, org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java
=> avoid reflection

org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/JavaVersionExtendedTest.java
simplify JavaVersionExtendedTest
=> simplify JavaVersionExtendedTest

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccess2ForTest.java, org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccess2PerformanceTest.java, org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccess2Test.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java
[#1911] performance optimization
EclipseResourceFileSystemAccess2.hasContentsChanged
=> [#1911] performance optimization EclipseResourceFileSystemAccess2.hasContentsChanged

Jenkinsfile, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202212.target, releng/org.eclipse.xtext.target/pom.xml, releng/org.eclipse.xtext.tycho.parent/pom.xml
[eclipse/xtext#2120] prepare r202212 target
=> [eclipse/xtext#2120] prepare r202212 target

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/navigation/LinkToOriginProvider.java, org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/JdtHyperlinkFactory.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/AbstractHyperlink.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/HyperlinkHelper.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/navigation/JvmImplementationOpener.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextHyperlinkHelper.java
fix some jdt deprecations
mark more api for removal
=> fix some jdt deprecations & mark more api for removal

org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2, org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/GenerateStatemachine.mwe2, org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/META-INF/MANIFEST.MF
=> ditch old testing plugins

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2120] update 4.27 I-builds in latest
=> [eclipse/xtext#2120] update 4.27 I-builds in latest

org.eclipse.xtext.ui.codetemplates/src/org/eclipse/xtext/ui/codetemplates/GenerateCodetemplateLanguages.mwe2
=> no xbase in codetemplates

1-maven-build.sh
[#1954] fix local repo passing
=> [#1954] fix local repo passing

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
[eclipse/xtext#2120] update to 2023-03 in latest
=> [eclipse/xtext#2120] update to 2023-03 in latest

releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202212.target
=> format target files

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuildCancellationTest.java, org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/tests/ParallelBuildEnabledTest.java, org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/xtext/ui/ContentAssistTest.java, org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java, org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/GlobalRegistries.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java
remove more outdated code switches for old targets
=> remove more outdated code switches for old targets

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectClasspathChangeAnalyzer.java
[#1916] added testcase for javadoc change only
[#1961] experimentally fix it
=> Fix treatment for javadoc change only

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JREContainerProvider.java
Fix JREContainerProvider.getJREContainerEntry(IJavaProject) to also work with Java 11 and Java 17
=> Fix JREContainerProvider.getJREContainerEntry(IJavaProject) to also work with Java 11 and Java 17

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/IntegrationTest.java
ignore hidden projects in build order tests
=> ignore hidden projects in build order tests

org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/IntegrationTest.java, org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/EMFBasedPersister.java, org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/MockableTextViewer.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/DefaultUiModule.java, org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/DefaultXbaseUiModule.java, org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/templates/XtextTemplateContextTypeRegistryTest.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/Activator.java, org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextUiModule.java
Better handling of some more deprecations
=> Better handling of some more deprecations

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewSorter.java
=> Fix ViewerSorter deprecation

org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/ClassFileBasedOpenerContributor.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/StorageBasedTextEditorOpener.java
Fix deprecated IDE.getEditorDescriptor
=> Fix deprecated IDE.getEditorDescriptor

releng/org.eclipse.xtext.contributor/Xtext.setup
=> fix outdated webtools

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202203.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202206.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202209.target, releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r202212.target
[eclipse/xtext#2118] update to orbit 2023-03
=> [eclipse/xtext#2118] update to orbit 2023-03

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/outline/AbstractOutlineWorkbenchTest.java, org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/preferences/PreferenceStoreAccessTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting/PreferenceStoreWhitespaceInformationProvider.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/FixedScopedPreferenceStore.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/PreferenceStoreAccessImpl.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/PreferenceStoreAccessor.java, org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/RailroadViewPreferences.java
fix Default/Instance/Configuration Scope deprecations
=> fix Default/Instance/Configuration Scope deprecations

README.md
Addresses #1989 
Signed-off-by: Elie Richa <richa@adacore.com>
=> Update README.md with known Tycho issue

releng/org.eclipse.xtext.contributor/Xtext.setup
=> add args4j to oomph

releng/org.eclipse.xtext.contributor/Xtext.setup
[eclipse/xtext-core#2019] update to lsp4j 0.20.0
=> [eclipse/xtext-core#2019] update to lsp4j 0.20.0

org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/workspace/EclipseSourceFolderTest.java, org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/workspace/EclipseSourceFolder.java
closes #1997
since for tests I need a project, I created a single test to speed up things
=> EclipseSourceFolder fixed getPath
